### ISSUE TITLE
Build out display for notes input

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#124]
When a user is adding a note to a support request, what should that look like?
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/362845317

**Comment by gujacq** [comment]
New screens for this. I've also added hot spots that are clickable.

What adding a new note looks like: https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232535

New note added confirmation:
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232534

Editing a newly added note:
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232899

Editing an inline note:
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232536

**Comment by gujacq** [comment]
@misternu

**Comment by jel535s** [comment]
Created as working issue #201
