### ISSUE TITLE
As a ___ user, I need to access account settings

### ISSUE THREAD

**Issue by gujacq** [MidwestAccessCoalition/lockbox_rails#127]
All Users:
- should be able to update name and password

Clinic Partner User:
- Update Clinic information: Clinic Name, Address, Phone
- Things that might be relevant in the future: Gestational limit, types of services and procedures provided, hours

MAC User:
- ~~Ability to update email address~~
- See what type of role they are, but not able to change unless they're admin level

**Comment by gujacq** [comment]
Clinic Partner User: https://invis.io/9EMYOUG7ZBA#/371460157_dashboard_-_Partner_User_-menu_Open-

MAC User:
Initial menu open - https://invis.io/9EMYOUG7ZBA#/361595345_dashboard_-_MAC_User_-menu_Open-

Then clicking into account settings - https://invis.io/9EMYOUG7ZBA#/371461199_dashboard_-_MAC_User_-menu_Open_-_Account_Settings-

**Comment by BintLopez** [comment]
This looks great. Just one thing -- we need Account Settings to be available to a partner user as well:

See the below for where we'd expect to see an "Account Setting" button
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/5728859/63229641-4793cf80-c1c8-11e9-89a7-037835c7cb51.png">

**Comment by rebeldroid12** [comment]
Actually, let's have edit contact info stuff in it's own separate page/form for the organization info similar to account settings edit. this should have a different button and should not be displayed as a default when we click on the settings icon. @gujacq

**Comment by rebeldroid12** [comment]
For desktop:
- keep hamburger menu
- clinic name + contact info
- update password
- update contact info
- log out

For Mobile:
- tuck tabs under, same as desktop.

**Comment by gujacq** [comment]
Updated here: https://invis.io/9EMYOUG7ZBA#/371460157_dashboard_-_Partner_User_-menu_Open-

Screenshots:

<img width="1018" alt="Screen Shot 2019-08-19 at 9 28 42 PM" src="https://user-images.githubusercontent.com/33872753/63312878-6da09900-c2c8-11e9-8f27-6f9099861535.png">
<img width="1015" alt="Screen Shot 2019-08-19 at 9 28 48 PM" src="https://user-images.githubusercontent.com/33872753/63312879-6da09900-c2c8-11e9-8da3-b06a1df0dea9.png">
<img width="1017" alt="Screen Shot 2019-08-19 at 9 28 55 PM" src="https://user-images.githubusercontent.com/33872753/63312880-6da09900-c2c8-11e9-985d-da90a99ac23b.png">

**Comment by gujacq** [comment]
Related to #134. See that ticket for the mobile designs

@BintLopez @rebeldroid12
