### ISSUE TITLE
As a MAC user I'd like to view the lockbox partner contact info

### ISSUE THREAD

**Issue by gujacq** [MidwestAccessCoalition/lockbox_rails#128]
Need to add contact information at the top of each page

<img width="785" alt="Screen Shot 2019-06-30 at 2 48 54 PM" src="https://user-images.githubusercontent.com/33872753/60401391-535b0200-9b46-11e9-8efc-cb5b55ec7762.png">

**Comment by gujacq** [comment]
Contact information can be seen on this page:
https://invis.io/9EMYOUG7ZBA#/361599959_dashboard_-_MAC_User_-Single_Lockbox_Partner-

All pages under those four tabs should have the same info up top. I need to retroactively apply this to all the designs, which might take a bit but just an FYI.

**Comment by gujacq** [comment]
to-do:

- need to update that fourth tab on all MAC user pages to say "Manage Lockbox Partner"
- contact information on Manage Lockbox Partner page needs be editable

**Comment by gujacq** [comment]
The fourth tab on all MAC user pages now says "Manage Lockbox Partner"

Contact info is editable as well:
Page with contact editable (emails are in blue with an edit icon) - https://invis.io/9EMYOUG7ZBA#/365422459_dashboard_-_MAC_User_-invite_Lockbox_Partner_User-

Page with editable field once the user clicks to edit - https://invis.io/9EMYOUG7ZBA#/372540798_dashboard_-_MAC_User_-invite_Lockbox_Partner_User_-_Edit-

**Comment by rebeldroid12** [comment]
Looks good! 
@BintLopez 
I would like to discuss more about the manage user logs in particular the `actions`. 
- what is a locked account and how would we know it is in this state?
- what is an unlocked account and how would we know it is in this state?
- how do we resend invites?
- say we edit an email, does it send an invite automatically on edits?
