### ISSUE TITLE
MAC user view of a single lockbox partner

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#13]
This is the management interface for a MAC user adding a new Lockbox Partner to the app or managing an existing lockbox. From the page of a single lockbox partner, I should be able to....

- add an amount of cash to a partner's lockbox
  - fields on form:  amount, lockbox partner
- invite lockbox partner users to the app
  - input fields -- email, name
- see action/transaction history for the lockbox
- click a button to add a support request to the lockbox

**Comment by gujacq** [comment]
https://invis.io/9EMYOUG7ZBA#/359239804_dashboard_-_MAC_User
