### ISSUE TITLE
Reorganize the views

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#130]
Need to reorganize given the way we're organizing the app navigation

These are the types of views we have....

All Users
- top nav bar

MAC User
- zoomed out dashboards (not scoped to a particular lockbox)
- scoped to a particular lockbox
  - sub nav for that lockbox
    - 4 available actions (all activity, file support request, add cash, manage lockbox settings)
  - lockbox header

Partner user
- subnav (two tabs -- action needed, all activity)
- lockbox header
- partner alerts

Also correct the app fonts
- Source Sans is our font

**Comment by jel535s** [comment]
@BintLopez is this ticket from the backlog still relevant, or has it maybe been solved/is being solved based on these navigation tickets?
 #83 
#121 
#175 
#280

**Comment by BintLopez** [comment]
Yeah, I don't think this is still relevant. Will close. Thanks for flagging @jel535s
