### ISSUE TITLE
Mobile navigation for MAC and Partner users

### ISSUE THREAD

**Issue by gujacq** [MidwestAccessCoalition/lockbox_rails#134]
Need to design a mobile navigation solution for MAC and Partner users. Prioritize MAC users.

**Comment by gujacq** [comment]
For MAC user:

Mobile menu open when not on a specific partner page. The dark blue indicates the current page the user is on. In this instance, they've opened the menu from the main dashboard - https://invis.io/9EMYOUG7ZBA#/372542665_mobile_Menu_-_MAC_User_-from_Home-

Mobile menu open when the user IS on a specific partner page. Dark blue indicates current page - https://invis.io/9EMYOUG7ZBA#/372542666_mobile_Menu_-_MAC_User_-lockbox_Specific-

Mobile menu one page deep when the user clicks "Account Settings" - https://invis.io/9EMYOUG7ZBA#/372542666_mobile_Menu_-_MAC_User_-lockbox_Specific-

**Comment by gujacq** [comment]
Mobile menu for partner clinic here: https://invis.io/9EMYOUG7ZBA#/374918390_dashboard_-_Partner_User_-menu_Open_Mobile-

**Comment by BintLopez** [comment]
For account settings, users should only be able to update their name and password. A user should not be able to update their email address.

For partners, the user should be able to update their name and password as well as the partner address and contact information.

**Comment by rebeldroid12** [comment]
Actually, let's have edit contact info stuff in it's own separate page/form for the organization info similar to account settings edit. this should have a different button and should not be displayed as a default when we click on the settings icon. @gujacq

**Comment by gujacq** [comment]
For lockbox partner mobile view: https://projects.invisionapp.com/d/main#/console/12893192/374918390/build

<img width="341" alt="Screen Shot 2019-08-19 at 9 31 50 PM" src="https://user-images.githubusercontent.com/33872753/63313040-c6703180-c2c8-11e9-99c4-4f5f626bbfea.png">

(see #127 for interactions. Should be the same between mobile and desktop with the exception of the tabs being tucked under in mobile)

**Comment by gujacq** [comment]
Running out of steam, so I'm going to tackle the MAC user side of things later

**Comment by gujacq** [comment]
MAC user settings:

View for what you see when open:
<img width="1045" alt="Screen Shot 2019-08-25 at 5 49 58 PM" src="https://user-images.githubusercontent.com/33872753/63656956-e7b99d80-c760-11e9-9dd8-0392310652f6.png">

https://invis.io/9EMYOUG7ZBA#/371461199_dashboard_-_MAC_User_-menu_Open_-_Account_Settings-

View for what happens when you click on "Edit Name" button:

<img width="1045" alt="Screen Shot 2019-08-25 at 5 50 04 PM" src="https://user-images.githubusercontent.com/33872753/63656975-f99b4080-c760-11e9-9f73-f6f681c2f389.png">

https://invis.io/9EMYOUG7ZBA#/361595345_dashboard_-_MAC_User_-menu_Open-

The update password is the same as see in the partner clinic (reference #127)

**Comment by gujacq** [comment]
Here are the views for the MAC user in mobile:

From the dashboard: 

<img width="366" alt="Screen Shot 2019-08-25 at 5 52 52 PM" src="https://user-images.githubusercontent.com/33872753/63657003-3404dd80-c761-11e9-8200-59f7d728ba4e.png">

https://invis.io/9EMYOUG7ZBA#/372542665_mobile_Menu_-_MAC_User_-from_Home-

....and once clicked in to a specific lockbox partner:
<img width="362" alt="Screen Shot 2019-08-25 at 5 53 59 PM" src="https://user-images.githubusercontent.com/33872753/63657015-5ac31400-c761-11e9-8041-a87c6161c4c8.png">

https://invis.io/9EMYOUG7ZBA#/372542666_mobile_Menu_-_MAC_User_-lockbox_Specific-

**Comment by rebeldroid12** [comment]
partially responsive (on mobile):
- nav bar diff sizes
- text overlapping
- heading didn't reach across screen

**Comment by rebeldroid12** [comment]
@gujacq for partner view: https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/374918390_dashboard_-_Partner_User_-menu_Open_Mobile- `Lockbox Partner Name 1` should be the partner user's name (Sally Snakes) and she should be able to update her name

**Comment by gujacq** [comment]
Closing as this has been addressed in #196
