### ISSUE TITLE
Thoroughly QA reconciliation

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#140]
Currently seeing some interesting behavior around reconciliation of lockboxes, especially when there are pending tasks present

**Comment by jel535s** [comment]
Notes from 8/25 meeting: needs test scenarios.  Bug has shown up in Reconciliation.  Balance results don’t match when we create fake support requests.  Balance on Reconciliation might factor in Pending requests when it shouldn’t be.

- Designing test cases
- Getting someone set up to do manual testing
- Doing manual testing
- Creating and running automated tests

Time estimate: 24 hours

**Comment by BintLopez** [comment]
There is a bug with reconciliation where a lockbox transaction with a negative amount can be created. This should not be the case.
