### ISSUE TITLE
Implement new partner user onboarding flow

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#141]
As a lockbox partner user, when I am invited to the app, I should go through the following flow...

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/5728859/60774094-a0098480-a0d4-11e9-92ce-bd7542611775.png">

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/5728859/60774097-a8fa5600-a0d4-11e9-8cba-559592325f49.png">

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/5728859/60774100-badbf900-a0d4-11e9-90d4-0ca03036ea4d.png">

**Comment by kyaroch** [comment]
@BintLopez Seems like we should be prompting the user to set a password here too, shouldn't we? They'll only have an undisclosed temporary password set at this point.

**Comment by kyaroch** [comment]
Also, a user could have a name set at this point (although it's not guaranteed). Do we want to prefill the Name field with an existing name? What about email?

**Comment by kyaroch** [comment]
Conclusions from discussion with @gujacq and @BintLopez:
* Name should not be prefilled, and we should not allow a MAC user to set a name when creating the user
* Email should be displayed on the form, but not editable
* Remove the paragraph under "Account Creation" from the view for successful account creation

**Comment by kyaroch** [comment]
Resolved by https://github.com/MidwestAccessCoalition/lockbox_rails/pull/172
