### ISSUE TITLE
Add tracking number to add cash

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#145]
## Context
As a partner user, I want to be able to see a tracking number for checks being sent to our lockbox, so that I can keep an eye out for them in the mail.

## Process
In the current production instance at https://mac-lockbox.herokuapp.com/ sign in as a MAC user.  Click on "View Lockbox Partner Details" for a lockbox partner, then select the "Add Cash to a lockbox" option in the top bar.  Screenshot under resources for that page.
When submitting a cash add, notice that there is only 1 field, the amount of cash added.

## Acceptance Criteria/Definition of Done
When submitting cash to a lockbox partner as above, we want the form to add one more optional field for a tracking number for checks, or confirmation name for online processing.  Title for field: "(Optional) Tracking number for checks/Confirmation number for online processing"

## Resources
Add cash page from a MAC user perspective:
![image](https://user-images.githubusercontent.com/53353956/74112665-1dfaa600-4b64-11ea-9315-ee94b72ccf5e.png)

**Comment by AG-Sile** [comment]
tech notes: add a new table, tracking_infos connected to lockbox_actions with provider_name and tracking_id
