### ISSUE TITLE
Representing transactions visually with +/-/()

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#151]
Lockbox Actions that represent debits -- should should a minus sign (support requests OR reconciliation adjustments)
  - should pending support requests be visually different (in parenthesis?)
  - should we make this red?
Lockbox Actions that represent credits -- should show a plus sign (add cash OR reconciliation adjustments)
  - should pending add cash be visually different (in parenthesis?)
  - should we make this green?

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/5728859/62012927-dc6b5600-b151-11e9-96ce-74360623da89.png">

**Comment by BintLopez** [comment]
@gujacq we did a little bit of thinking about how to display line item lockbox actions in the all activity view. Would love your thoughts!

**Comment by BintLopez** [comment]
Display of the lockbox partner activity table (screenshot above) should be changed such that...

- all debit amounts are in red and are prepended with a minus sign (we expect all support requests and some reconciliation adjustments to be debits)
- all credit amounts are in green and are prepended with a plus sign (we expect all add cash and some reconciliation lockbox actions to be credits)
- move the amount column on this table one space right so that status and amount are beside each other. This will make columns:  Date, Activity, Status, Amount, Client, Actions
- all lockbox actions in canceled status should have a gray background

**Comment by BintLopez** [comment]
The relevant models for this task are:

- LockboxAction - https://github.com/MidwestAccessCoalition/lockbox_rails/blob/master/app/models/lockbox_action.rb
- LockboxTransaction - https://github.com/MidwestAccessCoalition/lockbox_rails/blob/master/app/models/lockbox_transaction.rb

**Comment by nsiwnf** [comment]
Pending code-review
