### ISSUE TITLE
New lockbox partner initialization flow- ready to implement

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#152]
This task encompasses designing and implementing the flow for adding a new lockbox partner as an admin users.

As an admin user, I should be prompted to do the following after filling out the new partner form:
- add users to the lockbox
- add cash to the lockbox

Special cases:
- When a lockbox has no users yet, the add cash form should be disabled.

**Comment by jel535s** [comment]
The second half of this ticket is handled under #52

**Comment by gujacq** [comment]
Here's a link to the lucidchart: https://www.lucidchart.com/invitations/accept/01a9497a-eb2c-4c6d-a2f9-69271ecb9757

Attaching a PDF as well.

Purple = MAC coordinator view
Blue = partner clinic view
Dotted outline = action happening outside of the app

[New lockbox partner initialization flow.pdf](https://github.com/MidwestAccessCoalition/lockbox_rails/files/3563987/New.lockbox.partner.initialization.flow.pdf)

**Comment by jel535s** [comment]
@gujacq - this flow looks great, approved!  Can you make a couple mockups of the messaging for:
- Partner sees the following confirmation message on dashboard: Welcome message, any actionable items needed, "action needed" and "all activity" tab access
- Coordinator app gets alert that partner clinic received cash.  Message should be: "[Lockbox Partner] has confirmed their cash is received, and you can now send them Support Requests."
- "File a support request" tab is live after confirmation (and one where it isn't live).  
- Partner receives in-app notification of money added.  Should reuse the "confirm deposit" message.
- After 3 days of inaction, app pings MAC coordinator to check on clinic.  This should be a red constant bar which appears at the top of the "All Activity" page which is accessed when a MAC user clicks on "View Lockbox Partner Details".  ALSO:
- For UX, this message should also appear on the main page, which is where they go to send Support Requests.  Message should be: "[Lockbox Partner] is not active, has not confirmed cash for X days."
(note for future:  once dropdown for clinics clarifies whether they are active, this last messaging can be redacted from the app)

**Comment by gujacq** [comment]
Partner sees the following confirmation message on dashboard: Welcome message, any actionable items needed, "action needed" and "all activity" tab access: https://invis.io/9EMYOUG7ZBA#/367770324_dashboard_-_Partner_User_-account_Creation_Confirmation-

<img width="862" alt="Screen Shot 2019-09-15 at 5 18 28 PM" src="https://user-images.githubusercontent.com/33872753/64928364-d9e5be00-d7dc-11e9-9073-402b588eb84e.png">

---

Coordinator app gets alert that partner clinic received cash. Message should be: "[Lockbox Partner] has confirmed their cash is received, and you can now send them Support Requests." (Should happen on both the dashboard and specific lockbox partner page)

On dashboard, this messaging should be at the top of the page - https://invis.io/9EMYOUG7ZBA#/384005936_dashboard_-_MAC_User_-cash_Added_Alert-

<img width="1070" alt="Screen Shot 2019-09-15 at 5 46 52 PM" src="https://user-images.githubusercontent.com/33872753/64928645-d3f1dc00-d7e0-11e9-9721-5dea53853b64.png">

On specific lockbox partner page, it should be this same design, except for the *first* cash added instance, the messaging should be "[Lockbox Partner] has confirmed their cash is received, and you can now send them Support Requests." - https://invis.io/9EMYOUG7ZBA#/370234473_dashboard_-_MAC_User_-cash_Added_Confirmation-

<img width="539" alt="Screen Shot 2019-09-15 at 5 40 46 PM" src="https://user-images.githubusercontent.com/33872753/64928590-fcc5a180-d7df-11e9-94e7-382d55789a48.png">

---

"File a support request" tab is live after confirmation (and one where it isn't live)

Any tabs that are inactive should be grey. Not going to add a complete separate page for this to avoid confusing, but here's a screenshot. Grey is #5B616B

<img width="1014" alt="Screen Shot 2019-09-15 at 5 33 39 PM" src="https://user-images.githubusercontent.com/33872753/64928530-131f2d80-d7df-11e9-8186-a039e13158b5.png">

---

Partner receives in-app notification of money added. Should reuse the "confirm deposit" message:** https://invis.io/9EMYOUG7ZBA#/359242753_dashboard_-_Partner_User_-confirm_Deposit-

<img width="815" alt="Screen Shot 2019-09-15 at 5 28 27 PM" src="https://user-images.githubusercontent.com/33872753/64928454-401f1080-d7de-11e9-9afa-1659a5105571.png">

---

After 3 days of inaction, app pings MAC coordinator to check on clinic. This should be a red constant bar which appears at the top of the "All Activity" page which is accessed when a MAC user clicks on "View Lockbox Partner Details". Copy should say: "[Lockbox partner] has not confirmed cash in [X] days. Please check in with them for confirmation." - https://invis.io/9EMYOUG7ZBA#/384006192_dashboard_-_MAC_User_-cash_Confirmation_Alert-

<img width="542" alt="Screen Shot 2019-09-15 at 5 51 11 PM" src="https://user-images.githubusercontent.com/33872753/64928711-b2452480-d7e1-11e9-8331-7e63253eff96.png">

**Comment by jel535s** [comment]
Design above are looking good- this is ready to implement!
