### ISSUE TITLE
Account settings should only allow user to change name, not email

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#153]
A user should not be able to change their email in the system. In the case that somebody does need to change their email, the workaround will be to create a new account and lock the old one.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/5728859/62013206-f2c6e100-b154-11e9-8a05-f3ba87e425fc.png">

**Comment by BintLopez** [comment]
FWIW -- this is the current state of this form, so this task will also encompass building out this form style

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/5728859/63656333-08312a00-c758-11e9-811d-16f24175670b.png">

**Comment by kyaroch** [comment]
The appearance of the edit password form (`app/views/devise/passwords/edit.html.erb`) was updated in https://github.com/MidwestAccessCoalition/lockbox_rails/pull/172; the same HTML/CSS should be usable here.

**Comment by BintLopez** [comment]
This issue is blocked by #134

**Comment by gujacq** [comment]
I've updated the designs in #134. Shouldn't be a blocker any longer!

**Comment by BintLopez** [comment]
These are links to the relevant designs:  https://github.com/MidwestAccessCoalition/lockbox_rails/issues/134#issuecomment-524671006

**Comment by jel535s** [comment]
Time estimate: 8 hours

**Comment by arches** [comment]
Closed in favor of #196
