### ISSUE TITLE
Partner and user offboarding workflows

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#154]
Need to think through how we want to deactivate users/partners.

**Comment by jel535s** [comment]
Preliminary workflows here.  I need to verify our data responsibilities, regarding archiving records once users or partners are off-boarded from the lockbox program.
[MAC App Offboarding Workflows.pdf](https://github.com/MidwestAccessCoalition/lockbox_rails/files/3538372/MAC.App.Offboarding.Workflows.pdf)

**Comment by jel535s** [comment]
V2 of #349 
MAC admin users, as built under #349 should be able to delete partner/clinic accounts.

Adding functionality to the Admin Dashboard regarding deleting partners?  Or perhaps this will go under the Partner Details page
- New Admin tier users should be able to fully delete partners/clinics
- New Admin tier users should be able to lock/unlock partner/clinic accounts

**Comment by gujacq** [comment]
## Context
Once someone is off-boarded, what information should be retained, what should that view look like, how accessible should it be, how long should this data stay, and how are we using this data (should check with finance and Diana on this). Also thinking about soft-deleting on the dev side.

## Process
[ ] Check with Diana and finance on needs
[ ] Design out UI for this
[ ] Create and spec ticket for development


## Acceptance Criteria/Definition of Done
[ ] Finalizing our policy around building out the admin v2 dashboard


## Resources
Reference ticket #349 and the workflow PDF attached above

**Comment by jel535s** [comment]
We are ready to proceed to step 2 of the above checklist- Design Out UI for this.
MAC Leadership and Finance agreed that they want us to keep the info on that each lockbox’s life history forever, while deleting PII. This data is fine to be de-identified and kept with only the Client ID- they are more interested in trends and reporting bulk numbers than tracking individual transactions. Soft delete would work well: where we keep the lockbox partner's transaction data accessible to the Finance Export built in #351, but deactivate that partner's logins and remove them as an option to send funds to.
It would also be fine to eventually set up a regular recurring export to Airtable if holding all of the data in Lockbox is unwieldy over the years, or slows down the app.
Next week I plan to complete the attached workflows, and then spec out tickets for:
- any missing functionalities in the app
- a training doc for MAC users offboarding a lockbox

**Comment by jel535s** [comment]
Worked on workflow charts in Lucidcharts, not yet completed.

**Comment by jel535s** [comment]
On-boarding flowchart ready:
[New Lockbox Partner On-boarding flow.pdf](https://github.com/MidwestAccessCoalition/lockbox_rails/files/5685753/New.Lockbox.Partner.On-boarding.flow.pdf)

**Comment by jel535s** [comment]
All tickets created, and workflows completed and added to Documentation!
