### ISSUE TITLE
Add all support requests view for MAC users

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#155]
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/5728859/62013270-987a5000-b155-11e9-98a4-6c93fd8afe18.png">

## Questions for user testing
* which support requests do we want to show in this view (only pending?)
* do we only want to the most recent X support requests?
* is it useful to see the balance here?

**Comment by jel535s** [comment]
This seems to be a duplicate of https://github.com/MidwestAccessCoalition/lockbox_rails/issues/61

I've also added these questions into the documentation for issue #156

**Comment by BintLopez** [comment]
Note -- the word "Clinic" is used in this table in the mockup. However, let's go with the term "Partner" as not all lockbox partners will necessarily be a clinic.

**Comment by jel535s** [comment]
Time estimate: 8 hours
