### ISSUE TITLE
User testing session with coordinator and partner

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#156]
Need user testing session with coordinators and at least one partner (perhaps a partner that's been waiting in the wings)

**Comment by jel535s** [comment]
https://docs.google.com/forms/d/1C24bC3U9Kv63U2MGCBfOspLV65jUmCzbkRos2h0m9Tk/edit?usp=sharing
For users testing with a test operator, on their own time.

**Comment by jel535s** [comment]
[MAC Dropbox App User Testing Script.pdf](https://github.com/MidwestAccessCoalition/lockbox_rails/files/3465046/MAC.Dropbox.App.User.Testing.Script.pdf)
[MAC Dropbox App User Testing Script.docx](https://github.com/MidwestAccessCoalition/lockbox_rails/files/3465047/MAC.Dropbox.App.User.Testing.Script.docx)
For user tests with a dev team test operator- pdf and doc versions

**Comment by jel535s** [comment]
From Slack:  we will likely use partner testers from Spiral, Choices, and the Ryan Center.  We will want MAC user testers to be Veronica at minimum and possibly also a volunteer coordinator.

**Comment by jel535s** [comment]
Summary sheet for collating all user test results
[MAC dropbox user test results summary sheet.docx](https://github.com/MidwestAccessCoalition/lockbox_rails/files/3465153/MAC.dropbox.user.test.results.summary.sheet.docx)

**Comment by jel535s** [comment]
Roll these questions into script/form for MAC users: https://github.com/MidwestAccessCoalition/lockbox_rails/issues/61#issue-440491645

**Comment by jel535s** [comment]
Summary of user testing results: https://drive.google.com/file/d/19uud1GNJsv16V7phRO69ycFPx45jFtO4/view?usp=sharing
