### ISSUE TITLE
Determine & implement system generated notes

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#157]
1. Tech team best guess at what these should be. What do we think should be logged as system generated notes?

2. Ask Veronica if our guesses are missing anything and/or useful?

3. Implement the logging

**Comment by rebeldroid12** [comment]
What triggers note generation?
- Creation of a support request (automatic)
- Status changes (automatic)
- Edit of a support request (automatic) - could just be something generic like `Support Request Updated`, user can manually add a note about what the changes were so it's known
- user adding a note (when users click add/save note)

**Comment by rebeldroid12** [comment]
@BintLopez when you get a chance can you review.

**Comment by BintLopez** [comment]
@misternu -- fyi

**Comment by jel535s** [comment]
Created tickets for these and confirmed with @BintLopez that these are the messages we want.
