### ISSUE TITLE
Create a manual for the lockbox for the partner's perspective

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#170]
blocked: need to take screenshots when v1 of app is done.

**Comment by rebeldroid12** [comment]
Partner user:

- How to get started
- Onboard (emails)
- How to log in 
- Log in trouble shooting
- over view of main
- All activity
- View details of support requests
- Action needed
- How to reconcile
- How to confirm deposit
- How to change status of support request
- Cancel
- completed
- Making notes


https://docs.google.com/document/d/1e0dNPTYg37nR1GTyBtPMS47lVqB_l7T5XSZGOh2ysP0/edit

**Comment by gujacq** [comment]
@jel535s Is this something I can help with?

**Comment by jel535s** [comment]
Created first draft of copy.  Need to wait for MVP publish to update screenshots: https://docs.google.com/document/d/1bhUsBvOoS8E15s8XPrQMejrZONrp-DuZJ42AjPf2odw/edit?usp=sharing

**Comment by jel535s** [comment]
Done!  And linked on help page in app: https://docs.google.com/document/d/1bhUsBvOoS8E15s8XPrQMejrZONrp-DuZJ42AjPf2odw/edit?usp=sharing
