### ISSUE TITLE
Create a manual for the lockbox for the MAC user's perspective

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#171]
blocked: need to take screenshots when v1 of app is done.

**Comment by rebeldroid12** [comment]
MAC user:

- How to get started
- Onboard (emails)
- How to log in
- Log in trouble shooting
- Reset password
- Unlock instructions
- Confirm instructions
- Main overview of main index
- View lockboxes
- View individual lockbox
- View details of support requests
- How to file a support request
- How to add a clinic (admin only?)
- How to offboard a clinic (admin only)
- How to offboard a user (admin only)
- How to add a partner to clinic
- How to view all lockboxes
- How to access/update account settings
- Edit name
- Edit password
- How to send money to clinic/deposit money to clinic



https://docs.google.com/document/d/1e0dNPTYg37nR1GTyBtPMS47lVqB_l7T5XSZGOh2ysP0/edit?usp=sharing

**Comment by gujacq** [comment]
Same - @jel535s Is this something I can help with?

**Comment by jel535s** [comment]
Started a first draft of copy. Need to wait for MVP publish to update screenshots: 
 https://docs.google.com/document/d/1GEq8hbnjmH_4xq1WFgvuVrLMSTU1knjHLrKZyVqKzcY/edit?usp=sharing

**Comment by jel535s** [comment]
Done!  And linked to the help page in app: https://docs.google.com/document/d/1GEq8hbnjmH_4xq1WFgvuVrLMSTU1knjHLrKZyVqKzcY/edit?usp=sharing
