### ISSUE TITLE
Support request should be able to be editable

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#173]
## Context
Currently, there's a dead link to allow a MAC user to edit a support request. The view for editing needs to be built out.

## Process
When logged in a MAC user, navigate to one single support request in a given lockbox. Click the edit button. That link should render the form shown here:  https://invis.io/9EMYOUG7ZBA#/370233487_dashboard_-_MAC_User_-File_Support_Request_EDIT-

 Note-- this should render the form for a new support request.

## Acceptance Criteria/Definition of Done
What do you want to happen?

- A MAC user can edit a submitted support request in pending status.
- Canceled and completed requests should *not* have the option to edit
  - Edit Support Request button should be grayed out when the support request status is "completed" or "canceled"
- Note -- the form to edit a support request should not include updating the status (awaiting mockups for updating status)

## Resources
Related design task -- https://github.com/MidwestAccessCoalition/lockbox_rails/issues/88

**Comment by jel535s** [comment]
Time estimate: 4 hours, EOD Sep 1

**Comment by jel535s** [comment]
More design links here: 

What adding a new note looks like: https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232535

New note added confirmation:
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232534

Editing a newly added note:
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232899

Editing an inline note:
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232536
