### ISSUE TITLE
As a system, When a mac user adds a new lockbox user I want phone number intake to be strict

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#174]
## Context

Currently it's the wild west with adding phone numbers you can add any format of numbers and dashes. We need a standard. Perhaps 773-555-5555 or only numbers 7735555555. We need strict conditions. 

## Process
Navigate to `Add a new lockbox partner` and test it out locally!

## Acceptance Criteria/Definition of Done
You can only add phone numbers in one way.

## Resources
Add screenshots/mocks if relevant
Add relevant labels

**Comment by jel535s** [comment]
Time estimate: 4 hours of work

**Comment by arches** [comment]
Here are some ways we could handle it! 😂 https://qz.com/679782/programmers-imagine-the-most-ridiculous-ways-to-input-a-phone-number/amp/

**Comment by scottyschup** [comment]
Done as part of https://github.com/MidwestAccessCoalition/lockbox_rails/pull/242
