### ISSUE TITLE
As a partner, I don't know which tab I'm in.

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#176]
## Context
When you click on action needed or all activity, you don't know which tab you are in.

## Process
go to the partner view and click on a tab: `http://localhost:3000/lockbox_partners/1` 

## Acceptance Criteria/Definition of Done
It is clear which tab you are on.

## Resources
![partner_tabs](https://user-images.githubusercontent.com/5873894/63230469-93e40d00-c1d2-11e9-9249-5e161d2c7108.png)

**Comment by BintLopez** [comment]
This PR will address this to an extent in that it separates out the two links... https://github.com/MidwestAccessCoalition/lockbox_rails/pull/181/files
![image](https://user-images.githubusercontent.com/5728859/63647426-d8960980-c6e6-11e9-9436-3bea18aa73d5.png)

But, this behavior is quite buggy. Just noticed that if you click back and forth between Action Needed and All Activity you can still end up in the state where both links have active styles 
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/5728859/63647430-f4011480-c6e6-11e9-8df6-0c7a6b1809e6.png">

**Comment by BintLopez** [comment]
Have tried to reproduce this behavior in staging and am unable to. This should be resolved.

**Comment by BintLopez** [comment]
Closing.
