### ISSUE TITLE
As a partner, I can change the status of a support request

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#177]
## Context
Currently, we can't update the status. 
We need a drop down for statuses (complete, canceled). 

## Process
On the partner view, go to a support request and click on view details. You cannot update the status.

## Acceptance Criteria/Definition of Done
Status can be changed and is reflected in the database.

**Comment by jel535s** [comment]
This looks like a duplicate of issue #29 in To Do?
