### ISSUE TITLE
As a coordinator, when I add cash to the lockbox the amount should not be updated yet.

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#183]
## Context
Currently when you add cash to the lockbox the status automatically gets set to `pending` and the amount in the lockbox is automatically updated.

## Process
Click the details for a lockbox partner, navigate to the `Add cash to lockbox` tab and add cash. 
View amount will update

## Acceptance Criteria/Definition of Done
Only when it's been confirmed should the total be updated.

**Comment by BintLopez** [comment]
- This task entails changing the balance calculation to not take pending add cash lockbox actions into account.
- Currently the balance calculation factors in 'pending' actions by default unless we pass in an argument to disable this.
- Will need to change the balance calculation to treat pending support client actions differently than add cash actions that are pending.

**Comment by BintLopez** [comment]
When a pending cash addition exists for the lockbox, that amount should be displayed underneath (or beside) the actual balance in parentheses...

```
$200
(pending + $1000)
```
