### ISSUE TITLE
As a partner, I need a confirmation of deposit to be sent so I can confirm.

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#184]
## Context
Coordinators can add cash to the partners but there is message asking to confirm the deposit. 

## Process
As a coordinator, add cash to a partner. As a partner, look at the logs. The total is updated and there is nothing for a partner to confirm the deposit. So technically, this could lead to the situation where no money was received but our system says it was. 

## Acceptance Criteria/Definition of Done
Trigger a confirmation of deposit to be sent when cash has been added by the coordinator. This message will alert the partner to be on the look out for the deposit in the mail. 

## Resources
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/359242753

**Comment by BintLopez** [comment]
When a MAC user adds cash to a lockbox...
- the lockbox partner should receive a notification email that cash is on the way
- an alert should appear on the lockbox partner's screen prompting them to confirm the cash has been received
