### ISSUE TITLE
As a partner, when there are no pending support requests, what should I see?

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#185]
This is what the action items display looks like when the partner does not have any upcoming lockbox requests:

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/5728859/63640142-6f6cb280-c662-11e9-9ef3-441c3342ddfe.png">

What should this look like?

**Comment by gujacq** [comment]
We should double check with client coordinators, but there should be messaging that says there aren't any support requests and that they're caught up with everything.

**Comment by gujacq** [comment]
Copy:

> There are no support requests in your queue. You're caught up with everything!
