### ISSUE TITLE
MAC coordinator notification upon support request status change

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#187]
## Context
As a MAC coordinator, I should receive an email notification when the status changed to canceled or completed from the support request

## Process
- Log in as a partner user
- Complete/cancel a support request
- check mailcatcher to see if the notification email comes in for the coordinator

## Acceptance Criteria/Definition of Done
Email subject:  "[partner name] Support Request [ID] - [new status]"
Email copy:  
> Status request [ID] was changed from [original status] to [new status] by [user] on [date].

## Resources
Add screenshots/mocks if relevant
Add relevant labels

**Comment by BintLopez** [comment]
Need to add the text of the mailer. For a first implementation, let's just get the functionality in there with a very simple email.

**Comment by rebeldroid12** [comment]
`Support request [ID] was changed from [original status] to [new status] by [user] on [date].`
