### ISSUE TITLE
As a mac user, I want to be able to see all users belonging to a partner

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#191]
## Context
Currently when we navigate to `Manage lockbox partner` for a given partner we only have the ability to invite new users to the partner but we don't have a way to view existing users in that same tab.

## Process
Go to `View Partner lockbox details` then click on the `Manage lockbox partner` tab. you'll see no view for existing users belonging to a partner.

## Acceptance Criteria/Definition of Done
A section at the bottom for managing users.
The table/log should have the following columns:
- Date Added (timestamp of when a mac user submitted the form above)
- Name (I think this is something that the user will update and we should reflect it? initially this might just be blank?)
- email (maybe just display this for now)
- status (**pending** for when it's been sent but not confirmed, **accepted/confirmed** when user has confirmed)
- action (**lock account**/**unlocked** when status is **accepted/confirmed**, **resend** when status is pending)

V2:
- be able to update the email field and resend invite?

@BintLopez i think this could be broken down into v1 goals and further iterations?

## Resources
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/365422459
![current_view](https://user-images.githubusercontent.com/5873894/64039814-22d11d80-cb21-11e9-8bae-d3c9d51f25e8.png)

**Comment by BintLopez** [comment]
Yes, I think this looks great. I think we can chunk this up into:

- list all the users for a lockbox partner
- implement lock/unlock account action
- implement resend invite action

**Comment by BintLopez** [comment]
show_all_users_for_lockbox

**Comment by BintLopez** [comment]
for user management, we're going to axe editing an email. If a user's email needs to be edited, the admin can just invite a new user under that email account and lock the existing account

**Comment by BintLopez** [comment]
Quick question re status @jel535s @gujacq .... I'm wondering if we want to use "active" instead of "accepted" or "confirmed". Thoughts?

**Comment by BintLopez** [comment]
(went with "active")
