### ISSUE TITLE
Rename objects

### ISSUE THREAD

**Issue by arches** [MidwestAccessCoalition/lockbox_rails#198]
_Ticket to memorialize an in-person conversation between @arches and @BintLopez (and @misternu tangentially)_

We aren't thrilled with all of our object names.  We would prefer to change them sooner rather than later, but renaming objects often requires a massive PR that causes a bunch of conflicts unless we coordinate carefully.  So, first order of business is to align on the names we want.  There are three sources of confusion:

## Lockbox vs Partner

A lockbox and a partner are two very separate concepts, currently combined in the app.  As a new contributor, I (@arches) kept thinking "wait which of these objects represents the actual lockbox?!"  Since all the objects have the Lockbox prefix, the `LockboxPartner` object actually reads as just "partner".

Splitting these apart into separate concepts would improve readability/grokability, but there really aren't any properties of the lockbox separate from the partner (yet) so there isn't a strong requirement pushing us to further refine this area.  Removing the Lockbox prefix could simplify things, though it would further subsume the lockbox concept inside Partner.

## Action/Transaction

Currently, `LockboxAction` represents the top-level change to a balance, and `LockboxTransaction` represents a categorization of different amounts within that top-level change.  E.g. a $30 debit action might include a $10 gas transaction and a $20 food transaction.

Both these words are pretty generic, and thus don't really describe their use very well.  They also don't imply any relationship between each other.  No specific solution has yet presented itself, but our discussion included action replacements like `accounting_event`, `entry`, or `operation`.  Our transaction replacements included `item`, `line_item`, `breakdown_item`, `component`, `element`, `chunk`, `detail`.

## Lockbox Prefix

Argument against prefixing: More a source of frustration than confusion.  Prefixing everything with `Lockbox`, especially when "lockbox" is also itself a domain concept, muddles the object model.  All the code starts to blur together, because you have to read halfway through the word before you get to the important part.

Argument for prefixing: If the repo was named "beanshooter" or something random, would we want to keep the prefixing?  Definitely more likely.  If we start managing more aspects of partner/client support through the app, the prefix becomes more useful.

Another (weaker) argument in favor is that Transaction (and maybe Action) are reserved words.

**Comment by rebeldroid12** [comment]
data model: https://dbdiagram.io/d/5d3df1d1ced98361d6dd131e

since we are refactoring we should also double check that all the fields are needed/are not missing.
