### ISSUE TITLE
investigate impact of lockbox action as primary object (vs support request)

### ISSUE THREAD

**Issue by arches** [MidwestAccessCoalition/lockbox_rails#199]
We've been proxying a lot of stuff through SupportRequest, which has generally felt kind of awkward.  Also, not all LockboxActions have a SupportRequest.  It feels like LockboxAction is actually a more central object, and SupportRequest is some additional metadata about a specific type of LockboxAction.

Before committing to this mental shift, we want to gain an understanding of its impact on the codebase.  E.g. is this something where we have a bunch of tech debt to clean up?  If so, do we have to do it all at once?

**Comment by jel535s** [comment]
This is related to @emmajuettner 's work on #577 and designs from #578
