### ISSUE TITLE
Implement MAC user global forms header

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#204]
As a MAC user, when I'm not looking at a particular lockbox and I click on either the "File Support Request" or "Add Lockbox" buttons I should see the forms to do either of those things under the buttons. The button that I clicked should have an indicated notch (little triangle underneath it) to indicate which form I'm on.

See:  
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/365424955
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/365424956

## Acceptance Criteria
- Support Request and Add a new lockbox forms from the MAC user dashboard should match the mockups in the links above.

**Comment by nsiwnf** [comment]
This is what I see right now - so should these tabs initially be "closed" and then when the user clicks on it, it will show whats in the mocks including all the support requests that are there right now? 
<img width="695" alt="Screen Shot 2019-10-19 at 11 00 12 AM" src="https://user-images.githubusercontent.com/34173394/67149391-a70d6a80-f25f-11e9-86a6-3e98699d47bc.png">

**Comment by BintLopez** [comment]
@nsiwnf ^^ yes! That is correct! They're in 'closed' state when we're looking at all the support requests or all the lockbox partners, and have the triangle only when either filing a support request or creating a new lockbox is happening.

**Comment by gujacq** [comment]
The wifi situation is failing me so I can't update Invision at the time but here's as screenshot of the back to dashboard link

<img width="1053" alt="Screen Shot 2019-11-10 at 5 32 54 PM" src="https://user-images.githubusercontent.com/33872753/68552760-544b4c80-03e0-11ea-80bc-222f5761026c.png">

**Comment by nsiwnf** [comment]
@gujacq @BintLopez I wasn't able to get the triangle to have a border, but I did get just a blue triangle. Should I move forward with this or just leave it without the triangle?
<img width="626" alt="Screen Shot 2019-11-30 at 1 57 41 PM" src="https://user-images.githubusercontent.com/34173394/69906519-8dd8fd00-1379-11ea-8a81-27d4ef760a72.png">

**Comment by BintLopez** [comment]
I personally am cool with this to get us to launch and then we can go back and revise/tweak the styles later. @gujacq you cool with that?
