### ISSUE TITLE
CORS issue loading font-awesome icons

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#208]
Currently the font-awesome icons are not rendering. JS console in the browser shows a CORS issue...

![image](https://user-images.githubusercontent.com/5728859/64928892-d73a9700-d7e3-11e9-8bea-78f9c79a0e27.png)

![image](https://user-images.githubusercontent.com/5728859/64928906-005b2780-d7e4-11e9-87b8-e35785be335b.png)

**Comment by BintLopez** [comment]
This is an issue in heroku; not with local dev

**Comment by kyaroch** [comment]
I was unable to replicate this on my Linux laptop, using either Firefox or Chromium. I will try it on my Mac desktop and report back.

**Comment by BintLopez** [comment]
Chris was able to reproduce on his machine. This is an issue still.
