### ISSUE TITLE
Follow-up fixes for support request edit form

### ISSUE THREAD

**Issue by kyaroch** [MidwestAccessCoalition/lockbox_rails#210]
https://github.com/MidwestAccessCoalition/lockbox_rails/issues/173/https://github.com/MidwestAccessCoalition/lockbox_rails/pull/178 added functionality for editing support requests. However, these bugs/missing features must still be resolved:

- There is currently no way to remove a transaction from a support request
- The total amount is not displayed below the transaction list
- The urgency flag does not populate in the form correctly

**Comment by BintLopez** [comment]
See all comments from this PR:  https://github.com/MidwestAccessCoalition/lockbox_rails/pull/178
