### ISSUE TITLE
Build notifications for MAC user/partner: new note on a Support Request

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#211]
### Context
As a MAC user and Partner, I want to know when a note is added to a Support Request.
This is blocked by #201 currently.

### Process
Build an emailer when a note is added to a Support Request:
An email is sent to the Lockbox partner and CC'd to the MAC coordinator.  This email can be text-only.  The email copy reads:
**Subject:** A new note was added to Support Request [ID]
**Body:** [the text of the note that was added]  

### Acceptance Criteria/Definition of Done
When a MAC user or Lockbox Partner creates a new note on a Support Request, a system-generated note is created on the Support Request page as described in #201 .  An email containing the text of the note is also sent to both the Lockbox Partner and to the MAC Coordinator.  

### Resources
#201 is covering the system-generated notes for this functionality.

**Comment by kyaroch** [comment]
As amended in conversation with @jel535s and @BintLopez: the body should be something to the effect of "<name> added a note to support request <id>", and should not contain the text of the note.

**Comment by kyaroch** [comment]
These emails should probably not be sent for system-created notes, although we're not 100% sure that this is a universal rule.
