### ISSUE TITLE
Build notifications for MAC user/partner: changes to a Support Request

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#212]
### Context
As a MAC user and Partner, I want to know when  a support request is edited in any of the following ways:
Support Request object:
client alias
client ref ID
urgency flag
OR
Lockbox Action:
pick up date
OR
Lockbox transactions:
-amount breakdown- this will need to be written as "check last amount, if different, write a note"

### Process
Perhaps by incorporating the Papertrail audit gem, build two pieces of notification when a Support Request is created:
1.  System-generated note, visible on the Support Request page when opened by either MAC users or Lockbox partners.  
For edits to the client alias, the note should read: "The client alias for the Support Request was changed on [date + time] by [user] from [previous alias] to [changed alias]."
For edits to the client reference ID, the note should read: "The client reference ID for this Support Request was changed on [date + time] by [user] from [previous ID] to [changed ID]."
For edits to the urgency flag, the note should read: "The urgency flag for this Support Request was changed on [date + time] by [user] from [previous flag] to [changed flag]."
For edits to the pickup date, the note should read: "The pickup date for this Support Request was changed on [date + time] by [user] from [previous date] to [changed date]."
For edits to the total amount, please note, this is more complicated and will need to be to be written as something like, "check last amount, if different, write a note".  This system-generated note should read: "The total amount for this Support Request was changed on [date + time] by [user] from [previous amount] to [changed changed amount]."
Right now, when you create a note without a user, it automatically creates a system-generated note.

2. An email is sent to the Lockbox partner and CC'd to the MAC coordinator.  The email copy reads:
For edits to the client alias, the email should read: 
**Subject:** Support Request [ID] client alias was changed.
**Body:**  The client alias for the Support Request was changed on [date + time] by [user] from [previous alias] to [changed alias].
For edits to the client reference ID, the email should read: 
**Subject:** Support Request [ID] client reference ID was changed.
**Body:**  The client reference ID for this Support Request was changed on [date + time] by [user] from [previous ID] to [changed ID].
For edits to the urgency flag, the note should read: 
**Subject:** Support Request [ID] urgency flag was changed.
**Body:** The urgency flag for this Support Request was changed on [date + time] by [user] from [previous flag] to [changed flag].
For edits to the pickup date, the note should read: 
**Subject:** Support Request [ID] date was changed.
**Body:** The pickup date for this Support Request was changed on [date + time] by [user] from [previous date] to [changed date].
For edits to the total amount, please note, this is more complicated and will need to be to be written as something like, "check last amount, if different, write a note".  The email should read:
**Subject:** Support Request [ID] date was changed.
**Bodyy:** The total amount for this Support Request was changed on [date + time] by [user] from [previous amount] to [changed changed amount].

These emails can all be text-only, no formatting needed.

### Acceptance Criteria/Definition of Done
When a MAC user or Lockbox Partner changes the above fields on a Support Request, a system-generated note is created on the Support Request page as described above.  An email containing the copy above is also sent to both the Lockbox Partner and to the MAC Coordinator.

### Resources
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232535 - for the system generated note design reference
Blocked by #173

**Comment by arches** [comment]
Pulling in an offline conversation, here's where I think we net out with regard to who receives emails about notes.  _Reminder: status changes to support requests generate notes, and these notes are the primary mechanism to send notifications about support request changes. Another reminder: support request creation is handled separately._

* All MAC users are emailed for every manual note
* Except, MAC users are not emails if they wrote the note
* All partners for a given lockbox are emailed for every note (system and manual)
* Lockbox manager `ENV['LOCKBOX_EMAIL']` does not receive email about any notes
* For any given note, a single email is sent with the relevant parties in the proper address fields

@jel535s @BintLopez I was wondering if it would be better to send individual emails so we don't end up leaking contact info, but for now we wouldn't have any situations of sharing contact info between partners and it's probably important for the partners to be able to reply to the email and get support?

**Comment by BintLopez** [comment]
Thank you for laying this out! Reviewed with @jel535s and these bullet points look great.

We discussed...
> I was wondering if it would be better to send individual emails so we don't end up leaking contact info, but for now we wouldn't have any situations of sharing contact info between partners and it's probably important for the partners to be able to reply to the email and get support?

We think that sending individual emails or bcc-ing all recipients is the way to go here. That way we can encourage folks to have these conversations in the app rather than email.

**Comment by arches** [comment]
Cool, easy change, I'll update the PR 👍 thanks

**Comment by arches** [comment]
haha of course when I say "easy" it turns out to be a little complicated 🙄Fixed in c534a5b3
