### ISSUE TITLE
Create new sort options on main Dashboard view

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#216]
### **Context**
MAC users want to be able to sort the Pending Support Requests view on the Dashboard by Coordinator and other fields [aka user who created the Support Request]

### **Process**
When signing in as a MAC user, I want to be able to sort the Support Requests visible under the Pending Support Request tab.  The most important way that I want to sort, is by Coordinator [aka user who created the Support Request].

We will need to replace the "Action" Column with a "Coordinator" Column.

We will need to add sort functionality to all columns, but at minimum, the new Coordinator column.

We will need to turn the entire row into a link which will take them to the View Details page of the Support Request.  This should be indicated visually when you mouse over the row, perhaps by underlining the text in the row.

### **Acceptance Criteria/Definition of Done**
When signing in as a MAC user, I should be able to sort the Dashboard table when in the Pending Support Requests view, and click on the row to get to View Details.

### **Resources**
Existing screen:  
![image](https://user-images.githubusercontent.com/53353956/65839446-4c719600-e2d3-11e9-8ff7-7685883c7fe6.png)

**Comment by gujacq** [comment]
Here it is: https://invis.io/9EMYOUG7ZBA#/386263477_dashboard_-_MAC_User_Dashboard_Support_Request_View

**Comment by gujacq** [comment]
passing back to @jel535s for review
