### ISSUE TITLE
MAC User Onboarding - how is this done?

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#219]
## Context
Thinking about creating screenshots/manuals and not sure how users get added to the system. Do we have 2 types of users? admin and coordinators?

## Resources
N/A

**Comment by rebeldroid12** [comment]
https://docs.google.com/document/d/1e0dNPTYg37nR1GTyBtPMS47lVqB_l7T5XSZGOh2ysP0/edit 

^ manual sections (please give input!)

**Comment by jel535s** [comment]
From discussion with Nicole:
There is only 1 level of MAC user.
Nicole adds users in console, then confirms them as a user and sends them an email asking them to go through the "forgot my password" flow.
@rebeldroid12 closing this ticket- for the manual, let's just skip this part.  No screenshots.
