### ISSUE TITLE
Input mileage for gas reimbursement

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#223]
## Context
The finance team needs to know mileage traveled when we are giving reimbursements for gas costs. This is so that they can calculate the IRS rate for gas reimbursements for accounting purposes.

Currently coordinators use TravelMath to calculate reimbursement rates and distance from point A to point B:  https://www.travelmath.com/cost-of-driving/

For finance team purposes, we should switch to the IRS reimbursement rate of $0.20 per mile (based of IRS medical purposes travel). Coordinators can then list the mileage and calculate the gas reimbursement amount off of that. This will give us more consistency across reimbursements and a more solid backup if we get reviewed in an audit.

## Process
Edit Support Request itemization fields as indicated on the mockups below.

## Acceptance Criteria/Definition of Done
Support requests that include gas mileage need to have a field that asks coordinators to type in round-trip mileage, and the support request form should then auto-calculate the IRS reimbursement amount ($0.20 per mile)

## Resources
Please see mockups linked below!

**Comment by gujacq** [comment]
@jel535s and @BintLopez 

Updated mocks to show what mileage could look like:
https://invis.io/9EMYOUG7ZBA#/370233487_dashboard_-_MAC_User_-File_Support_Request_EDIT-

It includes a new tooltip element (that prob needs to be spec'd out for another dev ticket). I've mocked this up:
https://invis.io/9EMYOUG7ZBA#/390629439_dashboard_-_MAC_User_-File_Support_Request_EDIT_-_Tooltip-

**Comment by BintLopez** [comment]
"This is calculated using the IRS reimbursement rate for medical purposes travel of $0.20 per mile"
