### ISSUE TITLE
Devise errors should not reveal which accounts are valid

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#232]
![image](https://user-images.githubusercontent.com/5728859/66277425-ffa63600-e863-11e9-9602-b04aeb229bcf.png)

**Comment by jel535s** [comment]
## Context
Currently a devise error reveals which accounts are valid.  We would prefer a more generic error message.

## Process
Recreate: Attempt to recover a password with an email that is not a currently active lockbox user.  

## Acceptance Criteria/Definition of Done
When a user enters an email address that is not currently an active Lockbox user address, they should see the following error message:  

“If an account exists for this email address, you will receive an email with account reset instructions.  If you do not receive that email, please double-check that you are entering the email address where you originally heard from Lockbox.”

## Resources
Current error message as of 12/1/19: 
![image](https://user-images.githubusercontent.com/53353956/69922236-53965b00-1460-11ea-98db-55c42fdbb019.png)
