### ISSUE TITLE
MAC users should receive a notification email for new partner user activation

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#258]
## Context
When a new lockbox partner user completes onboarding and activates their account, the MAC users  should receive an alert that the lockbox is ready for them to continue with set up.

## Process
When a new partner creates their password and the Lockbox for that Partner is changed from Inactive to Active in our database, an email should be automatically sent to the coordinator who created the partner in the app.  Using the copy below under "Resources", this email should tell the MAC user that they can now send cash- and eventually Support Requests- to the new partner Lockbox.

## Acceptance Criteria/Definition of Done
As a MAC user, add a new partner.  That triggers an email to the partner per #141 
As a partner, accept the invite.  Then, as a MAC user, you should have received some type of notification letting you know onboarding can continue.

## Resources
_Copy for email to MAC user:_
Good news!  The Lockbox for [partner name] is now active.  [User] has confirmed their email address.  You can now send cash to this Lockbox.  Once they have confirmed that cash is received, you will be able to send Support Requests as well.  Please sign in to the app to send cash to the Lockbox:  [link to app]

Thank you!

Midwest Access Coalition

If you have any other questions, please forward this email with your questions to lockbox@midwestaccesscoalition.org [mailto:lockbox@midwestaccesscoalition.org]

_end of email copy_

**Comment by jel535s** [comment]
Updated email copy and spec above!

**Comment by AG-Sile** [comment]
Tech notes: discussed with Nicole, going to add invited_by to lockbox_partner with a validation that the user that invited the lockbox_partner is an admin
