### ISSUE TITLE
Bug in MAC user all support requests view

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#262]
Currently, when a MAC user is on the dashboard and selects the view for "all support requests", the link in the row for the support request is broken

![image](https://user-images.githubusercontent.com/5728859/68829990-b2d62c00-0667-11ea-91fe-d112d4185ee2.png)

![image](https://user-images.githubusercontent.com/5728859/68830018-c7b2bf80-0667-11ea-8b41-e601010bebda.png)

**Comment by kyaroch** [comment]
I am unable to replicate this. @BintLopez, can you provide steps to replicate?
