### ISSUE TITLE
Limit amount of visible support requests from dashboard

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#266]
## Context
As a MAC user, when I look at the dashboard view, I will see all the historical support requests for that given lockbox partner per the below screenshot.

~-~Do we want to limit this to 3-5 of the most recent support requests? To either pending requests or the most X recent support requests regardless of status?~-~

This should only display the 3 most recent support requests.

## Process
Log into mac-lockbox.herokuapp.com, and create multiple support requests for one partner. Navigate to the main dashboard page and watch them proliferate.

## Acceptance Criteria/Definition of Done
From the dashboard view of all lockbox partners, only the 3 most recent support requests should be visible per partner.

## Resources
![image](https://user-images.githubusercontent.com/5728859/69015664-b1547e80-095b-11ea-9f46-81c60fd6f60a.png)

**Comment by jel535s** [comment]
@gujacq  and I both agreed in Slack- we want to limit this to display only the most recent 3 support requests.

**Comment by nsiwnf** [comment]
https://github.com/MidwestAccessCoalition/lockbox_rails/pull/291
