### ISSUE TITLE
Stylize error pages.

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#267]
## Context
Currently, we do not stylize any of our error pages. When in local development, we'll get an error page with a stacktrace (which is great for development purposes), but in production, we'll get a generic heroku error page.

## Process
To reproduce, navigate to a page in the app that does not exist... like /bleeps (see below screenshot)

## Acceptance Criteria/Definition of Done
Error page should read: "Something went wrong, please reach out to lockbox@MidwestAccessCoalition.org" and for UX, should show a random gif from @gujacq 's drive of options: https://drive.google.com/open?id=1Oyr7NkoonpLzVBY5xQ28kQjcQZUfR3iH 

## Resources
![image](https://user-images.githubusercontent.com/5728859/69015946-e9a98c00-095e-11ea-9eec-57608ee827ec.png)

**Comment by jel535s** [comment]
Based on in-person conversation with Nicole, we want this error message to read, "Something went wrong, please reach out to lockbox@MidwestAccessCoalition.org" ? 
I agree with the above, @gujacq - when you build the mockup, I am thrilled if we can make it cuter.  I know we don't have an art budget but maybe we can pull a graphic that is free for commercial reuse?  Also totally fine if we don't make it cute for the MVP though.

**Comment by gujacq** [comment]
Here is the link to the error page: https://invis.io/9EMYOUG7ZBA#/398801184_dashboard_-_MAC_User_-error- 

I think we could finesse the messaging a little bit to not sound so mechanic or abrupt?

I'm also uploading the gifs I found that might work for this page:
