### ISSUE TITLE
Clinic user can reconcile lockbox

### ISSUE THREAD

**Issue by kyaroch** [MidwestAccessCoalition/lockbox_rails#27]
As a clinic user, I want to log the amount of money in the lockbox once per month and make any necessary adjustments.

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/5728859/58386479-e9d75900-7fc5-11e9-9ba5-edcbe23bfd51.png">

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/5728859/58386494-14c1ad00-7fc6-11e9-9630-9697b1cbe1f9.png">

**Comment by BintLopez** [comment]
The reconciliation frequency should be configurable from the admin panel (feedback from V)

**Comment by BintLopez** [comment]
Admin user should be able to see who reconciled the lockbox and who okay-ed add cash and who completed support requests (feedback from V)
