### ISSUE TITLE
How should we handle notifications for the Lockbox manager -- should they be BCC-ed on every single support request?

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#272]

**Comment by jel535s** [comment]
@BintLopez I believe this was addressed in #212 and that we set it to notify Lockbox manager's every time a Support Request was created.  But if we did not already, then based on my app user testing with the coordinators I think we should build in that notification as well.

**Comment by jel535s** [comment]
Clarification:  "Lockbox manager = Veronica at MAC"

**Comment by BintLopez** [comment]
Reached out to V ... the lockbox manager _should_ be cc-ed on every new support request. The email address for this is `ENV['LOCKBOX_EMAIL']` aka the same email that receives low balance and cash added notifications
