### ISSUE TITLE
Notify MAC finance users when lockbox amount drops below $300

### ISSUE THREAD

**Issue by kyaroch** [MidwestAccessCoalition/lockbox_rails#28]
When the balance of any lockbox drops below $300, MAC finance users should be notified so that more money can be added to the lockbox.

**Comment by BintLopez** [comment]
Send email notification to mac users when a given lockbox partner balance drops below $300

**Comment by nsiwnf** [comment]
Check balance after lockbox transaction - if below $300, send email

**Comment by BintLopez** [comment]
This should be implemented as an observer/listening/callback action upon balance changing to below $300

Any subsequent support request that changes the balance further below $300 should send additional alerts to the finance team

**Comment by arches** [comment]
What email should be notified?

**Comment by jel535s** [comment]
Time estimate: 8 hours
Potential messaging:
"Heads up!  The lockbox at [partner name] is below $300 when taking into account all pending support requests.  Please send a check ASAP."  
I am also adding a question to my Veronica-user-test script, to specifically note if this messaging needs to be more specific.
