### ISSUE TITLE
Implement- Help/Support page

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#282]
## Context
For the MVP, we need to add a help/support contact page which is accessible by all registered and logged in users.

## Process
On both the MAC user side and partner user side, we need to add a button in the header which directs them to Help.  This page should have a link to the relevant manual, as well as the email and instructions for how to ask for help.  Copy and current app images are listed below in References.

## Acceptance Criteria/Definition of Done

Step 1- @gujacq - please mock-up placements in both the MAC user and partner user headers for a Help page button.  Also please mockup a short Help page using the copy below in Resources.

Step 1- dev team- please implement the copy/mockups as listed below.

## Resources

MAC user header currently in app:
![image](https://user-images.githubusercontent.com/53353956/69922656-cbb25000-1463-11ea-97bb-b9ebad49db94.png)

_MAC user help page copy:_
If you're having issues in the app, please check out our FAQ manual here first (LINK: https://docs.google.com/document/d/1GEq8hbnjmH_4xq1WFgvuVrLMSTU1knjHLrKZyVqKzcY/edit?usp=sharing)

If you aren't able to find the answer there, you can also email lockbox@midwestaccesscoalition.org

Partner user header currently in app:
![image](https://user-images.githubusercontent.com/53353956/69922715-7e82ae00-1464-11ea-8df8-715ece26d602.png)

_Partner user help page copy:_
If you're having issues in the app, please check out our FAQ manual here first (LINK: https://docs.google.com/document/d/1bhUsBvOoS8E15s8XPrQMejrZONrp-DuZJ42AjPf2odw/edit?usp=sharing)

If you aren't able to find the answer there, you can also email lockbox@midwestaccesscoalition.org

**Comment by gujacq** [comment]
@jel535s updated both views for support:

**Partner user:**
Header with "Get Support" link: https://invis.io/9EMYOUG7ZBA#/371460157_dashboard_-_Partner_User_-menu_Open-

Get Support page: https://invis.io/9EMYOUG7ZBA#/396818235_dashboard_-_Partner_User_-get_Support-


**MAC user:**

Header with "Get Support" link: https://invis.io/9EMYOUG7ZBA#/384004843_dashboard_-_MAC_User_-menu_Open-

Get Support page: https://invis.io/9EMYOUG7ZBA#/396818363_dashboard_-_MAC_User_-get_Support-

Feel free to reassign this to a developer if this is good!

**Comment by scottyschup** [comment]
Looks like this task was mostly completed (I'm guessing by @kyaroch given the activity on 12/22/19). All that's left to do is some CSS adjustments and replacing dummy links with real ones.
