### ISSUE TITLE
V2 Help page/ticketing

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#284]
## Context
For the 2nd Version of the app, we need to build out the help/support contact page which is accessible by all registered and logged in users.  This page needs to be updated to have a form which will automatically post to github as part of our ticketing process for issues.

## Process
The Help page should be updated to add a form which will automatically post to github as part of our ticketing process for issues.

## Acceptance Criteria/Definition of Done

Step 1- @gujacq - please mock-up a form for the help page.  This form should collect:

- _This copy at the top:_  
For MAC users:
If you're having issues in the app, please check out our FAQ manual here first [LINK: https://docs.google.com/document/d/1GEq8hbnjmH_4xq1WFgvuVrLMSTU1knjHLrKZyVqKzcY/edit?usp=sharing]
If you aren't able to find the answer there, you can also fill out this form and click submit to log your issue.  Our all-volunteer IT team will start work on it right away, but the issue may remain for some time depending on how heavy their workload is this week.  
For Partner users: 
If you're having issues in the app, please check out our FAQ manual here first [LINK: https://docs.google.com/document/d/1bhUsBvOoS8E15s8XPrQMejrZONrp-DuZJ42AjPf2odw/edit?usp=sharing]
If you aren't able to find the answer there, you can also fill out this form and click submit to log your issue.  Our all-volunteer IT team will start work on it right away, but the issue may remain for some time depending on how heavy their workload is this week.  
- user email address (ideally auto-fill)
- date/time (ideally auto-fill)
- Issue (long-form field)
- place to upload screenshots from phone or computer where they are accessing the app
- submit button
- _This copy at the bottom, near the submit button:_  If you need immediate assistance, please email lockbox@midwestaccesscoalition.org.

Step 1- dev team- please implement the copy/mockups as listed below.

## Resources

**Comment by gujacq** [comment]
Support form for partner clinics (though the design should be the same for MAC users, just different content—see Jesse's notes above): https://invis.io/9EMYOUG7ZBA#/404321025_dashboard_-_Partner_User_-get_Support-_2

What it looks like when someone uploads multiple files - https://invis.io/9EMYOUG7ZBA#/404321027_dashboard_-_Partner_User_-get_Support-_2_Screenshots

Confirmation screen - https://invis.io/9EMYOUG7ZBA#/404321026_dashboard_-_Partner_User_-get_Support-_2_Confirmation

**Comment by nsiwnf** [comment]
Technical question - Should these requests be stored in our DB or just make a github request to create an issue?

**Comment by jel535s** [comment]
@nsiwnf that's a good question and might pose security issues.  @gujacq and @BintLopez can we discuss this item at our data meeting on Sunday?

**Comment by nsiwnf** [comment]
Meeting minutes from Sunday 
- Look into Zapier integration
- We want to screen things like PII so it isnt shown openly

**Comment by jel535s** [comment]
We want this form to post to Slack, as any help request will probably require back and forth messaging to fully spec out the solution.  We want this to integrate to #lockbox-alerts, where @gujacq will prioritize and spec out tickets for the github manually, and tag in members of the tech team when technical advice is needed.

**Comment by gujacq** [comment]
This will be a google form to take advantage of scanning for malicious files. It still needed to route to Slack and integrate with #lockbox-alerts

**Comment by nsiwnf** [comment]
@BintLopez does MAC have an airtable or zapier acct rn?

**Comment by BintLopez** [comment]
Discusssed -- we're going to do google forms embed so that we aren't added more users to the MAC workspace.

**Comment by BintLopez** [comment]
Nicole to create the Zap to slack once the form is good to go
