### ISSUE TITLE
Email notifications from notes

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#295]
## Context
Follow up to https://github.com/MidwestAccessCoalition/lockbox_rails/issues/212, https://github.com/MidwestAccessCoalition/lockbox_rails/pull/288

This issue arose out of a discussion on the PR adding an email notification for support request updates:  https://github.com/MidwestAccessCoalition/lockbox_rails/pull/288/files#r355219911

Currently, creation of a new support request will trigger duplicative (but not identical emails)...

<img width="711" alt="image" src="https://user-images.githubusercontent.com/5728859/71278353-f97d0d00-231c-11ea-8250-dfbbdce0c564.png">

<img width="694" alt="image" src="https://user-images.githubusercontent.com/5728859/71278381-0d287380-231d-11ea-90ff-8517bb54d6b4.png">

### Potential solutions
- leave it and release with duplicative emails
- don't leave a note for support request creation
- leave a note but don't trigger a notification for support request creation
- don't send the specific support request creation alert
- different note types send different email templates

Option 1 -- leave it and release with duplicative emails
pros: speed, code simplicity
cons: this would be very confusing to the end user, afraid that too many email notifications off the bat will give users a poor first experience with the app

Option 2 -- don't leave a note for support request creation
pros: simplicity in the code
cons: audit trail of what happened on the support request is not visible to the end user

Option 3 -- leave a note but don't trigger a notification for support request creation
pros: flexibility for different 'types' of notes (logging vs alerts)
cons: notes used as both audit trail and comms between app users

Option 4 -- don't send the specific support request creation alert
pros: simplicity and standardized messaging across all notes
cons: from a user perspective, it does not make sense to receive one generic email for all types of notes ranging from support request creation, to changes to the case to status updates.

Option 5 -- different note types send different email templates
pros: makes note types and their email templates configurable, allows us to maintain a standardized treatment of notes where their notification behavior is determined by config
cons: would need to add this config and rework how we generate the email to leverage config, would need to introduce concept of note types or classifications

Broader questions:
- Should all notes result in an email notification?
- Should all notes result in identical email notifications?
- Do notes have types? (logging, support request creation, user note)
- Notes is also acting as an audit trail, is that a bad thing? The alternative is to leverage papertrail and query versions table directly... but that seems like a heavy handed approach

## Process
n/a

## Acceptance Criteria/Definition of Done
TODO -- fill this out based on discussion + decision about implementation

## Resources
n/a

**Comment by BintLopez** [comment]
I think we're going to need to be able to send different content for different types of notes. We already have a solid use case for that with Support Request creation vs updates vs 'another user left a note'. I think this will continue to be the case with anticipated future functionality like being able to tag another user directly to receive a notification.

**Comment by jel535s** [comment]
My personal vote is Option number 1 for MVP and backlog Option number 5 for post-release update.  We can discuss!

**Comment by kyaroch** [comment]
My thought is that we can exclude option #4 right off the bat - it should be very obvious when an email indicates the creation of a support request.

None of the others is _obviously_ the wrong choice.

**Comment by BintLopez** [comment]
After discussion with the group, we decided to proceed with option 3. This would add a little bit of complexity/tech debt but would be the cleanest and lowest effort way to ensure that we don't have the duplicative email behavior.

**Comment by jel535s** [comment]
Being resolved by #298

**Comment by arches** [comment]
If we're going to differentiate between different note types, then why not simply differentiate the SR Creation note alert into the email we want?  Otherwise we're still left with two approaches to alerts/notifications.

**Comment by arches** [comment]
Or to rephrase - I'm saying options #5 and #3 seem like identical work to me, and #5 seems like a more internally consistent approach.
