### ISSUE TITLE
QA new demo app against design mockups

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#309]
## Context
Some pages and flows in the demo/staging instance may not match our design mockups.  We need to go through with a detailed eye to catch any updates needed to match our design mockups.

## Process
Check https://demo-lockbox.herokuapp.com/ against https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/361595392?

## Acceptance Criteria/Definition of Done
All pages in demo/staging at https://demo-lockbox.herokuapp.com/ match https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/361595392?

## Resources
https://demo-lockbox.herokuapp.com/ is the demo/staging app
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/361595392 is where the design mockups are housed

**Comment by BintLopez** [comment]
Functionality to check...

**Login**
a user can...
- successfully log into the app
- reset their password
- receive an invitation and create an account
- NOT sign up for a new account without an invitation

**Admin Actions**
a user can...
- add a new lockbox partner
- add cash to a lockbox
- invite lockbox partner users to the app
- resend an invitation to a partner user's account
- lock/unlock a partner user's account
- file a support request for a lockbox partner
- update the status of a support request
- edit an existing support request
- add a note to a support request
- edit a note that they have authored on a support request
- delete a note that they have authored on a support request
- view all support requests across lockbox partners
- view all lockbox partners

**Lockbox Partner Actions**
a lockbox partner user can...
- confirm that they have received cash for the lockbox
- reconcile the lockbox
- update the status of a support request
- edit an existing support request
- add a note to a support request
- edit a note that they have authored on a support request
- delete a note that they have authored on a support request
- view all pending support requests for only their lockbox
- view all lockbox activity for only their lockbox

**Comment by BintLopez** [comment]
Want to log the results in here? https://docs.google.com/spreadsheets/d/1hgMfKV2EJBX0preL_Ftus-Oyi2F82A0q77QxvZff1DM/edit#gid=0

**Comment by jel535s** [comment]
Combined into #322
