### ISSUE TITLE
Adjust all date displays to be Month-DD-YYYY

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#313]
## Context
In QA-ing new demo app against design mockups, found that dates are displayed differently in the Partner view of All Activity than indicated on design mockups.  We want all dates to be displayed as Month-DD-YYYY the way they are in the design mockups.

This will probably be linked to and may be combined with #344 

## Process
Sign in to https://demo-lockbox.herokuapp.com/ as a non-MAC user (partner or vendor):  fluffy@catsclinic.com; password:  heytherefancypants4321
Click on "All Activity", and note that dates are displayed as format "YYYY-MM-DD".  Then click on "View Details" and note that dates are displayed the same here.
Notice in the design demo for the "View Details" page, https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/365423869 that months are spelled out with the format "Month DD, YYYY".  
Also in design demo for the "All Activity" page, https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/361595392 dates are displayed as M/DD/YY.
In the current Lockbox production instance at https://mac-lockbox.herokuapp.com/, dates on all screens are consistently all-numeric, displayed as format "YYYY-MM-DD".  We want all dates to be displayed as Month-DD-YYYY the way they are in the design mockups.

## Acceptance Criteria/Definition of Done
Adjust the date display in the production instance of the Lockbox app to display dates in the format of "Month-DD-YYYY".

## Resources
https://demo-lockbox.herokuapp.com/ 
and
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/365423869
![image](https://user-images.githubusercontent.com/53353956/72690765-1ad04500-3ae5-11ea-9712-3aac11f8bb82.png)

**Comment by gujacq** [comment]
Lets have the date displayed as in the designs (so Month-DD-YYYY) since it's easier to read

**Comment by nsiwnf** [comment]
@jel535s That circled date is the "Pickup Date", right? Should that be formatted as Month, DD YYYY as well?

**Comment by jel535s** [comment]
@nsiwnf that circled date is the Support Request Created date.  And yup, we would want that to be formatted as "Month DD, YYYY" as well.  Thank you!
