### ISSUE TITLE
Disable new user registration & handle nil user role

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#319]
## Context
Currently, it's possible for any user to register for the app at sign_up, log in, and see all lockbox partners. Sign up should be disabled and only admin users should be able to see all lockbox partners

![image](https://user-images.githubusercontent.com/5728859/73143341-832ba300-405e-11ea-8406-559dd31315bc.png)

## Process
- navigate to users/sign_up
- follow the sign in steps
- update the confirmed_at field on the user to Time.current on the backend or confirm via the email
- observe that you can log in and see a list of 

## Acceptance Criteria/Definition of Done
- Sign Up should not be an available action
- If a user has no role set, they shouldn't be able to see anything.

## Resources

**Comment by kyaroch** [comment]
I'll take a look at this soon if I have time. If someone else does this, suggestions:

1. The most obvious (probably best) approach is to override `#new` and `#create` in `Users::RegistrationsController` so they don't do anything. I don't think we use those routes for any functionality we want.
2. We should have presence and inclusion validations for `role` on the `users` model. No default value, though!
