### ISSUE TITLE
QA Plan for Release

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#322]
Acceptance criteria:
- all manual QA completed for launch
- audit of current test coverage of these features; logging todos from that

Working out of:  https://docs.google.com/spreadsheets/d/1hgMfKV2EJBX0preL_Ftus-Oyi2F82A0q77QxvZff1DM/edit#gid=0

Screenshots and rough bug log here:  https://docs.google.com/document/d/1SjemquYsuV26flN2v324FlpBB77ItXZPuXZw4AOeQHQ/edit#heading=h.f2gsbyk9m7an

Functionality to check...

**Login**
a user can...
- successfully log into the app
- reset their password
- receive an invitation and create an account
- NOT sign up for a new account without an invitation

**Admin Actions**
a user can...
- add a new lockbox partner
- add cash to a lockbox
- invite lockbox partner users to the app
- resend an invitation to a partner user's account
- lock/unlock a partner user's account
- file a support request for a lockbox partner
- update the status of a support request
- edit an existing support request
- add a note to a support request
- edit a note that they have authored on a support request
- delete a note that they have authored on a support request
- view all support requests across lockbox partners
- view all lockbox partners

**Lockbox Partner Actions**
a lockbox partner user can...
- confirm that they have received cash for the lockbox
- reconcile the lockbox
- update the status of a support request
- edit an existing support request
- add a note to a support request
- edit a note that they have authored on a support request
- delete a note that they have authored on a support request
- view all pending support requests for only their lockbox
- view all lockbox activity for only their lockbox

_Originally posted by @BintLopez in https://github.com/MidwestAccessCoalition/lockbox_rails/issues/309#issuecomment-580926405_

**Comment by jel535s** [comment]
Design mockups to check against here:  https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/361595392

**Comment by BintLopez** [comment]
Manual testing complete! All go-live checks have passed:
https://docs.google.com/spreadsheets/d/1hgMfKV2EJBX0preL_Ftus-Oyi2F82A0q77QxvZff1DM/edit?skip_itp2_check=true&pli=1#gid=0

Todos remaining:
- [ ] @BintLopez to audit existing automated test coverage and identify gaps/needs for more unit or acceptance tests
- [ ] @jel535s to audit app views to ensure we're matching the mockups

**Comment by jel535s** [comment]
Note: where a mockup did not exist for a given scenario, Nicole and I agreed to mark it as "matches mockups"

**Comment by jel535s** [comment]
Mockups have been thoroughly checked and any existing mis-matches have tickets created in Github and logged in the QA sheet.

**Comment by jel535s** [comment]
Confirmed with @BintLopez this was completed!
