### ISSUE TITLE
Users unable to update name

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#324]
## Context
Currently there's no way for the user to update their account name. (It's also currently possible for a user to create their account without putting in their name)

## Process
Log in as either an admin user or a partner user and try to update your name.
Log in as a brand new user to the app -- notice how you can leave the name blank when signing up

## Acceptance Criteria/Definition of Done
Users should be able to update their name through their account settings

**Comment by misternu** [comment]
The user edit and create pages were simplified from the devise forms to match design, we can either restore its other functionality or create a separate form for updating this user information.

**Comment by misternu** [comment]
resolved by #346
