### ISSUE TITLE
MAC user onboarding workflow missing items

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#329]
## Context
MAC user creation flow currently does not set role or name
It does not reroute past the onboarding route

## Process
- invite a new MAC user to the app and follow the onboarding flow, note how access is not correct

## Acceptance Criteria/Definition of Done
- need to set the user role upon creation
- need to allow for name input in onboarding (when setting the pword)
- need to reroute to the index

### for admin users
![image](https://user-images.githubusercontent.com/5728859/73587743-0f85fd80-4485-11ea-875a-7da81e6d3db3.png)

![image](https://user-images.githubusercontent.com/5728859/73587747-1a409280-4485-11ea-9b3d-ae7cefe8abb7.png)

![image](https://user-images.githubusercontent.com/5728859/73587751-2cbacc00-4485-11ea-95c9-ed6b0bbc02d2.png)

### for partner users
![image](https://user-images.githubusercontent.com/5728859/73587785-8f13cc80-4485-11ea-85c6-bb0f1399e6d8.png)

**Comment by kyaroch** [comment]
I'm attempting to investigate this, but I didn't realize the MAC user onboarding workflow existed, and I can't find it now. Is this still in a topic branch?

**Comment by BintLopez** [comment]
Yeah... I started a branch for this to create a workflow for this, but this task makes more sense to handle after we get basic user management into the app so that new admin side users can be added via the app UI and don't have to go through the dev team.

**Comment by jel535s** [comment]
Blocked by #349
