### ISSUE TITLE
Balance and reconciliation manual QA

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#333]
## Context
While QA-ing app functionality, I noticed some interesting behavior with reconciliation and balance. This task would be to do a thorough QA of balance over time with multiple accounting events.

## Process
- Spend 30 mins to an hour trying to break balance and reconciliation in the staging app.

## Acceptance Criteria/Definition of Done
- Attempt to break the balance and reconciliation
- Log any issues or weird behavior --  either in this issue or a separate follow up issues

## Resources

**Comment by jel535s** [comment]
We have robust testing and are confident this is no longer an issue.
