### ISSUE TITLE
Need to adjust copy of Account Creation Confirmed

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#341]
## Context
Currently, when a new MAC user confirms their account via their on-boarding email, they fill out and submit the  password form in the app.  The confirmation screen that appears when that form is submitted references two on-screen options which are not visible to the user.  We need to adjust the copy on this notification:
![image](https://user-images.githubusercontent.com/53353956/73616262-cfcf2b00-45d6-11ea-824e-5bfddc238fd3.png)

## Process
As a new user, when you receive your on-boarding email, click through to confirm your account.  Submit the password form, and view the green notification that appears.

## Acceptance Criteria/Definition of Done
New copy for notification:

"Success!  Your account has been created.  Please open the menu in the top right corner to use the Lockbox app."

Suppress the duplicate alert.

## Resources
https://mac-lockbox.herokuapp.com/ - prod instance

**Comment by BintLopez** [comment]
I think the actual issue here is that the subnav with those two options isn't showing on the onboarding page.

Also, the duplicate success alerts.

**Comment by kyaroch** [comment]
I'm pretty sure the subnav was not displayed because of a bug, which we have since fixed. We decided to suppress the duplicate notification, but not change the copy.
