### ISSUE TITLE
Add user managment for MAC users - Part 1

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#349]
## Context
- Need to add a new tier of MAC Admin users  
- Need to rename current tier of MAC users from "admin" to "coordinators"
- These new higher tier Admin users should have a different tier of access than coordinators.
- New tier users should be able to see MAC user information about login history / access logs
- New tier users should be able to add other MAC users through a UI

## Process
This ticket covers:
Building out the 2 tiers of MAC users as explained in Context above

## Acceptance Criteria/Definition of Done
Addition of a coordinator role, and movement of most existing MAC users to that role

Tests: 
Try to access this page as a coordinator level MAC login on the app (should **not** be able to access)
Try to access this page as an new Admin level MAC login on the app (**should** be able to access)

## Resources
"manage a partner" page for reference:
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/365422459

Mockups:
For the menu (with the "Admin Dashboard" button): https://invis.io/9EMYOUG7ZBA#/408360708_dashboard_-_MAC_Admin_-menu_Open-

For the admin dashboard: https://invis.io/9EMYOUG7ZBA#/408360709_dashboard_-_MAC_Admin_-admin_Dashboard-

**Comment by jel535s** [comment]
@gujacq can you add a design here for the new MAC Admin dashboard view as outlined above?  Let me know if you need any further clarification, I know this is basically a rough outline.

**Comment by gujacq** [comment]
view log in history:
- IP address
- Last logged in attempt (possibly drills down to last ten login attempts)
- Might not need a front end design for this

**Comment by jel535s** [comment]
Updated ask for design based on IRL conversation:
- Build a view for where to access the new Admin Dashboard (possibly a nav button)
- Build a view of the new Admin Dashboard, including:
  - add a new MAC user and determine their role (admin vs. coordinator)
A list of all MAC users which includes:
  - lock/unlock MAC users
  - view last log in and last log in IP for every user
  - the status of the user's account (locked/pending/active)
  - their current role and the ability to change it (between admin and coordinator)

**Comment by jel535s** [comment]
Spoke to Nicole and clarified that eventually this dashboard will also include finance reporting.

**Comment by gujacq** [comment]
Designs here:

For the menu (with the "Admin Dashboard" button): https://invis.io/9EMYOUG7ZBA#/408360708_dashboard_-_MAC_Admin_-menu_Open-

For the admin dashboard: https://invis.io/9EMYOUG7ZBA#/408360709_dashboard_-_MAC_Admin_-admin_Dashboard-

**Comment by jel535s** [comment]
How to deactivate partners will be scoped under #154 .  That may eventually be built into this dashboard, but it may also go under the Partner Details pages.

**Comment by gujacq** [comment]
Update: Not adding a gem, Manu building something separate

**Comment by BintLopez** [comment]
Manu & Nicole discussion about whether or not to use `cancancan` ...

Possibilities:
- DIY PORO code
- `cancancan` gem
- `pundit` gem

Talking through access
- partition based on dashboard access... 3 separate dashboards
  - admin dash
    - is admin?
  - coordinator dash
    - is coordinator or admin?
  - partner dash
    - is partner and has ownership (aka it's their lockbox)?

**Comment by misternu** [comment]
Per further discussion last week, this will not yet be hidden behind an access tier, all current admins will have access to the new feature:

* Admins should be able to see MAC user information about login history / access logs
* Admins should be able to add other MAC users through a UI

**Comment by gujacq** [comment]
We're ok with going live with the user management dashboard, but we will need to scope out a new ticket for tiers. Once we have a different system for user tiers, we'll need to scope that out. This will be a large change and will require a lot of QA.

**Comment by BintLopez** [comment]
Closing this ticket. This represents work completed to allow admin users to create other admin users (does not implement any user access tiers). Subsequent work represented in attached tickets.
