### ISSUE TITLE
Should partners be able to create Support Requests?

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#356]
## Context
Sometimes clients who are not currently working with MAC find out when they are further along than they thought, and partners need cash for the client to help them stay for an unexpected extra day.  Gas money and hotels are frequent requests with unexpected multiple-day procedures.

## Process
The current process is for the lockbox partner or client to reach out to MAC, and then the MAC coordinator would approve and create a Support Request for the client in the app.  [X] requested the ability to create and send a Support Request directly to MAC, on the lockbox partner's behalf.  This would re-order our normal on-boarding process somewhat.  Is this a feature we want to consider building out?

**Comment by gujacq** [comment]
We think this is a big question for ED and the coordinators. Could have implications for multi-tenant lockbox.

Will earmark for this if it's something that comes up in our lockbox partner interviews

**Comment by jel535s** [comment]
Per Finance and MAC leadership:  both agree that lockbox requests should come through MAC folks at the moment. So we will be closing this request.
