### ISSUE TITLE
Discovery: see what the `rails_admin` Gem can do for us

### ISSUE THREAD

**Issue by scottyschup** [MidwestAccessCoalition/lockbox_rails#361]
## Context
`rails_admin` is super easy to setup and creates a sysadmin type portal that could be great for prod eng and reporting type tasks. We just need to play with it more to see what it can do and what might be helpful for us. 

## Process
From https://github.com/sferik/rails_admin:
> Add `gem 'rails_admin', '~> 2.0'` to the Gemfile.
> Run `bundle install`
> Run `rails g rails_admin:install`; when prompted for namespace, just hit enter.
> Start Rails server and navigate to http://localhost:3000/admin

Then play around!

Aso, this is a great overview that only takes a few minutes to click through: https://www.slideshare.net/benoitbenezech/rails-admin-overbest-practices

## Acceptance Criteria/Definition of Done
Done when analysis has been completed and discussion with dev team has occurred.

If the consensus is to add it, discuss specifics about implementation and create follow-up implementation task(s).

##Resources

Related to #417

**Comment by gujacq** [comment]
Feeds into conversation about Admin Portal

**Comment by jel535s** [comment]
We have been able to manage any requests via console. We don't anticipate needing this.
