### ISSUE TITLE
Header nav menu open/close bug

### ISSUE THREAD

**Issue by scottyschup** [MidwestAccessCoalition/lockbox_rails#365]
## Context
There's currently a fun little bug that occurs when you complete a specific series of actions in the header nav area (see below).

## Process
As a Lockbox partner user (e.g. `fluffy@catsclinic.com`) logged in on the home page:
1. open the navbar (click the gear icon)
1. with the navbar still open, click the "All Activity" subnav button (the navbar should close)
1. now click the "Action Needed" subnav button and note:
   * The navbar flickers open and closed
   * Pressing "Action Needed" again will produce the same result a second time
   * _however_, any subsequent clicking on the subnav buttons does not

Without any investigation, I'm guessing some `toggle` function is getting double called—perhaps two event listeners are being fired, in which case adding `Event#stopPropagation` to the higher handler may resolve it. But not positive.

## Acceptance Criteria/Definition of Done
Buggy behavior is squashed. Code is merged to master.

## Resources
![header_navbar_flicker_bug_slower](https://user-images.githubusercontent.com/6441226/74615353-91ad2d80-50e5-11ea-9e78-b6902a0d979a.gif)

**Comment by mrbberra** [comment]
So: I think my best idea here is to write a bit of javascript that [runs before you leave the page](https://stackoverflow.com/questions/28627111/how-to-call-a-function-before-leaving-page-with-javascript) that sets the class on the `navbar-collapse` div to `collapse`. Not actually sure if this would fix it, and it seems a bit heavy handed. [Here](https://getbootstrap.com/docs/4.3/components/collapse/) are the bootstrap docs for the element, if that's helpful.

**Comment by gujacq** [comment]
@scottyschup, can you give an update on this? LMK if you have any blockers, or would like someone else to take a look!

**Comment by gujacq** [comment]
Ticket for this is in review for anyone but for @BintLopez if you want to take a look
