### ISSUE TITLE
Change logging from debug to warn in prod

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#366]
## Context
In production logs, email content is displayed in full text. By changing the logging settings to warn instead of debug, this content can stay out of the logs.

## Process
n/a

## Acceptance Criteria/Definition of Done
Body of mailgun emails should not display in production logs

**Comment by gujacq** [comment]
Nicole wants to ask engineering advice on this

**Comment by gujacq** [comment]
Team decision: This isn't immediately actionable and we don't anticipate this being a huge concern. Could be rolled into a larger examination and clean up to our logging settings: #468
