### ISSUE TITLE
System generated notes for updated support requests

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#368]
## Context
A few refinements of notes:
- Add punctuation at the end of each change noted in the update summary note text
- Show who made the update in the note text
- Handle updates to/from nil values or empty strings (play around with changing the urgency flag on a support request)

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/5728859/74688353-e5c71900-519c-11ea-98ed-00e461e41a22.png">

## Process
Update a support request and observe the notes that are generated.

## Acceptance Criteria/Definition of Done
- notes text should have punctuation for legibility
- notes should indicate _who_ updated the support request
- display "blank" for updates to/from nil or empty string

**Comment by gujacq** [comment]
@AG-Sile Can you provide an update to this ticket and any blockers you might have?

**Comment by jel535s** [comment]
@AG-Sile was working on this ticket, but we're opening it back up to the group to grab. Not sure where they left off so it might be best to consider this a fresh start.
