### ISSUE TITLE
Flash alerts are persistent

### ISSUE THREAD

**Issue by misternu** [MidwestAccessCoalition/lockbox_rails#37]
there is js in Jane that we can use for this, it's possible that this needs jquery

**Comment by BintLopez** [comment]
![image](https://user-images.githubusercontent.com/5728859/56714726-8e762a80-66ea-11e9-9ca9-b4042af3ca7a.png)

^^ also noticed this "true" along with a persistent flash alert -- I believe this was a timeoutable sign out
