### ISSUE TITLE
Make low balance trigger amount configurable per partner

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#371]
## Context
Lockbox finance team needs low balance alerts to be set at different amounts for different partners, so that they can send out payments proactively.
Edited 12/6 to include the below comments in this top comment so that it is ready to work!

## Process

- [x] Confirm with lockbox finance team the current 3 partners' trigger balances.

When a partner's balance reaches a certain amount, an email and in-app notification should be sent to the lockbox and finance managers.  This trigger amount will need to vary, based on the partner.  
This trigger amount also needs to factor in pending requests as if they were completed (which is the current workflow for visible balance at the top of the partner details page).
Notes from 11/15 meeting: FPA balance should be set at $750. $500 will be the default for new partners. All partner lockboxes should have the ability to be changed by MAC leadership.
We decided not to implement the ability for partners to adjust their own low balance alerts.
We decided to make this part of MVP Lockbox.

- [ ] Need to build in a field that MAC users can edit on the "partner management" view and on the "add a new lockbox partner" view, where they can set this trigger amount.

- [x] Need to design where this field shows up for MAC users -- in the onboarding form and in the partner management panel

- [x] Need to design how this shows up for a partner view so they're informed what the balance is (but cannot change it)

## Acceptance Criteria/Definition of Done

- [ ]  In the Manage Lockbox partner view, add a toggle where MAC users will set the "low balance trigger amount" for each partner on an ongoing basis.  

- [ ] On the Add a new lockbox partner" page at https://demo-lockbox.herokuapp.com/lockbox_partners/new add a required field to set the low balance trigger amount, as partners are created.  Field title copy should be "Lockbox Low Balance Alert Amount" with instruction text below that reads "When the lockbox balance reaches this amount, notifications will be sent to the lockbox finance team and coordinators to send out more money."

## Resources
This is related to https://github.com/MidwestAccessCoalition/lockbox_rails/issues/451

New design for Manage Lockbox Partner view:
https://invis.io/9EMYOUG7ZBA#/365422459_dashboard_-_MAC_User_-invite_Lockbox_Partner_User-

New design for Add New Lockbox Partner view:
https://invis.io/9EMYOUG7ZBA#/365424955_dashboard_-_MAC_-add_New_Lockbox_Partner-

**Comment by jel535s** [comment]
From Kate/Veronica, Low balance triggers should be set at:
FPA: $750
All other: $500

**Comment by gujacq** [comment]
Nicole wants to QA and review, but it's been merged

**Comment by jel535s** [comment]
Notes from 11/15 meeting: FPA balance should be set at $750. $500 will be the default, but all partners should have the ability to be changed by MAC leadership.
We decided not to implement the ability for partners to adjust their own low balance alerts.
We decided to make this part of MVP Lockbox.

**Comment by gujacq** [comment]
I'd like to talk through this more. 

Some notes to remind myself for Sunday: 
- The Manage Lockbox partner view link is broken right now
- The Add a new lockbox partner looks a bit different from the designs, so want to go over this
- The manage users view rn is at an individual level, so I'd like to know if we want this function at an individual level. Worth talking about how detailed we want this function.

**Comment by gujacq** [comment]
Added the low balance alert to both pages:

https://invis.io/9EMYOUG7ZBA#/365424955_dashboard_-_MAC_-add_New_Lockbox_Partner-

https://invis.io/9EMYOUG7ZBA#/365422459_dashboard_-_MAC_User_-invite_Lockbox_Partner_User-

![dashboard - MAC (add new lockbox partner)](https://user-images.githubusercontent.com/33872753/101290400-9b646680-37c7-11eb-885f-3fa33483a032.png)
![dashboard - MAC User (invite lockbox partner user)](https://user-images.githubusercontent.com/33872753/101290401-9bfcfd00-37c7-11eb-96a1-76c22bb30d29.png)

**Comment by nsiwnf** [comment]
1. What should the input look like here? Should we assume it's a dollar amount and/or allow decimals?
<img width="335" alt="Screen Shot 2021-02-14 at 2 28 53 PM" src="https://user-images.githubusercontent.com/34173394/107891138-9ca1c600-6ed1-11eb-9100-379df1f89a75.png">


2. Is it ok if the edit-amount goes to the existing "Update Contact Info" page?

**Comment by jel535s** [comment]
@nsiwnf  here are some answers!
1. This should be a dollar amount, no decimals needed as we're moving towards a whole dollar standard with #520 
2. Yes, your screenshot in Slack looks good to me

**Comment by BintLopez** [comment]
@jel535s -- should we make the whole dollar standard a configurable thing? Want to make sure we're not getting rid of a feature that other users with our new collab would actually want to use?

**Comment by jel535s** [comment]
@BintLopez - I think that's a great question to add to our customer/partner interviews as we gather user stories for the collab, for sure. But I feel ok with making it our standard in this case as Finance has only ever asked us to set low balance alert thresholds in whole dollar amounts.
