### ISSUE TITLE
Add instruction text for partner users on Edit Contact Info page

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#379]
## Context
Can likely combine with #382 
As a partner user, it isn't clear to me what format is needed in the phone number field, when I am editing my contact information.

## Process
Sign in as a partner user, then click the hamburger/gear icon in the top right.  Select Edit Contact Information.  Note that although there is a required format for the phone number field, that is not an instruction which is clear to the user.

## Acceptance Criteria/Definition of Done
Add the following text in lighter gray (Hex code 5B616B), in the "Phone Number" field where the user types in their number:
"Format: 3124567890"

## Resources
![image](https://user-images.githubusercontent.com/53353956/75122527-df84e100-5663-11ea-82de-7119e0c44cb3.png)

![image](https://user-images.githubusercontent.com/53353956/75122738-6cc93500-5666-11ea-8c56-808e724452b7.png)

**Comment by nsiwnf** [comment]
This looks like it's functioning as expected!
