### ISSUE TITLE
Investigate and remove double line showing up in Staging app

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#396]
## Context
In the staging version of the lockbox app, but not in the production version, a double black line is showing up in some views. (screenshot below in resources)

## Process
In the staging app, sign in as a MAC user.  Click on "View Lockbox partner details" for a partner, such as 'Owl Health Associates".  Note the double black line that shows up above the main data table.

In the production app, follow the same steps and note that the black line isn't doubled.

## Acceptance Criteria/Definition of Done
Only a single black line should show up here.  Track down where it's different between these versions on the app code, so that we don't inadvertently push a bug into production.

## Resources
Staging app:
![MAC screenshot](https://user-images.githubusercontent.com/53353956/76171623-4e316680-615b-11ea-9d77-48f840a6eab7.png)

Production app:
![image](https://user-images.githubusercontent.com/53353956/76171650-92246b80-615b-11ea-8de5-dc02b5632ff9.png)

**Comment by mrbberra** [comment]
I think I know what this is: I added an extra horizontal rule to this page in [this commit](https://github.com/MidwestAccessCoalition/lockbox_rails/pull/372/commits/9f5b24573b00280201ec9fba300656eca316be48). I'll make a fix.

**Comment by mrbberra** [comment]
#405 fixed this and was merged in.
