### ISSUE TITLE
Ensure sidekiq runs in prod

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#403]
## Context
Follow up to https://github.com/MidwestAccessCoalition/lockbox_rails/pull/380...
Currently sidekiq queue is not draining on prod; 
- make sidekiq queue drain on prod
- ensure sidekiq related tests pass locally

## Process
- Run tests locally... observe failures
- Recreate the issue on staging and deploy until it's fixed

## Acceptance Criteria/Definition of Done
- make sidekiq queue drain on prod
- ensure tests pass locally

**Comment by gujacq** [comment]
Kevin's looking at this ticket for review
