### ISSUE TITLE
Tool Tip for balance on Partner Details page

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#406]
## Context
As a partner or MAC user, I may be confused about how the app is calculating the balance on the partner details page.

## Process
As a MAC user: sign in, then click on "View Partner Details".  Notice the balance in the upper right hand of the page.
As a partner user:  sign in, and notice on the front page that there is a balance in the upper right hand of the page.

## Acceptance Criteria/Definition of Done
Add a tool tip icon next to the balance.  This will be a clickable icon with text that pops up when clicked.  We prefer a clickable icon rather than a hover-over text, for mobile and accessibility reasons.

The copy when the icon is clicked should read: "The balance here includes all cash in the partner lockbox, minus any Pending Support Requests."

## Resources
Invisio designs for this are in comments below.

Screenshot of current prod instance of app, from MAC user: 
![image](https://user-images.githubusercontent.com/53353956/77261785-13e9be00-6c5f-11ea-8c4f-2a647bb3970a.png)
Screenshot of current prod instance of app, from a partner user:
![image](https://user-images.githubusercontent.com/53353956/77261856-a9854d80-6c5f-11ea-931b-54b301547b0c.png)

**Comment by gujacq** [comment]
Example can be shown here:

Tooltip by the balance: https://invis.io/9EMYOUG7ZBA#/361599959_dashboard_-_MAC_User_-Single_Lockbox_Partner-

Tooltip activated: https://invis.io/9EMYOUG7ZBA#/410333892_dashboard_-_MAC_User_-tooltip-

**Comment by gujacq** [comment]
@jel535s assigning back to you for review!

**Comment by gujacq** [comment]
Need to figure out what the balance copy says

**Comment by BintLopez** [comment]
"The balance here includes all cash in the partner lockbox, minus any Pending Support Requests."

**Comment by rebeldroid12** [comment]
Balance does not display `$` -- will add!
