### ISSUE TITLE
Add new dropdown option for "phone" to Support Request Amount Breakdowns (MVP)

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#413]
## Context
Add a new "Support Type" to the Amount breakdowns when creating or editing a Support Request. The new Support Type should be "Phone". MAC has a couple of burner phones that we give to clients.  When added to a Support Request, this should have a default amount of $0, as it will not affect the Lockbox balance.

## Process
Sign in to the app as a MAC user, and click on "File a Support Request". Note under Amount breakdown that the dropdown is limited to: Gas, Parking, Transit, Childcare, Medicine, Food, Adjustment, Cash-Addition.
Screenshot below, under "Resources"

## Acceptance Criteria/Definition of Done
Add to this dropdown an option for "Phone".  When this option is selected from the dropdown, it should auto-fill the Amount field to the right as $0, and make it unchangeable (grayed out).

## Resources
![image](https://user-images.githubusercontent.com/53353956/78510537-6f39a700-775b-11ea-94bd-c4f4a7d0419a.png)

**Comment by gujacq** [comment]
Closing out because the work around for MVP should be leaving notes to the partner about in-kind items. Further discovery to be address in #414
