### ISSUE TITLE
Add user managment for MAC users - Part 2

### ISSUE THREAD

**Issue by gujacq** [MidwestAccessCoalition/lockbox_rails#417]
## Context
- Dependent on team decisions/closing of ticket #470 
- Need to add a new tier of MAC Admin users 
- Need to rename current tier of MAC users from "admin" to "coordinators"
- These new higher tier Admin users should have a different tier of access than coordinators.
- New tier users should be able to see MAC user information about login history / access logs
- New tier users should be able to add other MAC users through a UI

## Process
This ticket covers:
Building and implementing the new Admin dashboard on the MAC user view of the app, accessible only by the new tier of MAC Admin users  
#154 will look into how to offboard partner accounts.

## Acceptance Criteria/Definition of Done
Build a view of the new Admin Dashboard, including:
- Add a new MAC user and determine their role (admin vs. coordinator)
- And a list of all MAC users which includes:
         - lock/unlock MAC users
         - view last log in and last log in IP for every user.  This possibly drills down to last ten login attempts.
         - the status of the user's account (locked/pending/active)
         - their current role and the ability to change it (between admin and coordinator)
 (similar to the "manage a partner" page linked in Resources)  This Admin Dashboard page should only be permissioned to the new MAC Admin roles. 

Tests: 
Try to access this page as a coordinator level MAC login on the app (should **not** be able to access)
Try to access this page as an new Admin level MAC login on the app (**should** be able to access)

## Resources
"manage a partner" page for reference:
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/365422459

Mockups:
For the menu (with the "Admin Dashboard" button): https://invis.io/9EMYOUG7ZBA#/408360708_dashboard_-_MAC_Admin_-menu_Open-

For the admin dashboard: https://invis.io/9EMYOUG7ZBA#/408360709_dashboard_-_MAC_Admin_-admin_Dashboard-

Relates to #349

**Comment by gujacq** [comment]
Moving this back to "needs spec" column. We need to determine an tier matrix first: ticket #

**Comment by jel535s** [comment]
Adjusting scope per #470 : MAC Leadership guidance on this was that we don't need to focus on user tiers- the functionality to add/delete MAC users and see/adjust finance categories is ok to share with all MAC emails.
Based on the new scope, all activities this ticket describes were already built under ticket #349 - no additional user tiering is required.
