### ISSUE TITLE
Resolve outstanding issues with CSP

### ISSUE THREAD

**Issue by kyaroch** [MidwestAccessCoalition/lockbox_rails#419]
## Context
A content security policy was implemented in https://github.com/MidwestAccessCoalition/lockbox_rails/pull/321. However, some issues remain:

1. Currently, `script-src` includes `unsafe-inline`. This raises security issues, and we want to disable `unsafe-inline`. However, that currently breaks rails-ujs. In order to fix this, we need to enable nonce generation.
2. Some commented-out code config/initializers/content_security_policy.rb is now superfluous and should be removed.
3. We may want to take a different approach to enabling/disabling upgrade-insecure-requests based on environment.

## Process
N/A

## Acceptance Criteria/Definition of Done
What do you want to happen?
Possible fixes?

## Resources
Add screenshots/mocks if relevant
Add relevant labels

**Comment by BintLopez** [comment]
Discussed issued with UJS and nonce generation. Currently it appears that nonces are being generated but the CSP is not finding them upon form submission.

Todos:
- Explore whether out of the box Rails CSP can appropriately handle the nonce for us https://github.com/DCAFEngineering/dcaf_case_management/blob/master/config/initializers/content_security_policy.rb#L25

**Comment by BintLopez** [comment]
Also good find by @scottyschup https://github.com/rails/web-console/issues/242#issuecomment-597081402
