### ISSUE TITLE
Rework mobile nav for specific lockbox view

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#422]
## Context
Blocked by:  https://github.com/MidwestAccessCoalition/lockbox_rails/issues/423

As a fund user, when viewing a specific lockbox on mobile, the four subnav options are crowded and the lockbox partner header takes up too much space. The lockbox partner users have a similar mobile experience.

## Process
Rework the mobile nav and lockbox partner header to match the mockups below.

## Acceptance Criteria/Definition of Done
Mobile navigation and headers match the mockups. Desktop usability is not affected.

## Resources
- TODO -- add mockup links

**Comment by jel535s** [comment]
Duplicated by #481 , updating that ticket to include info from here.
