### ISSUE TITLE
Mobile experience audit

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#424]
## Context
Currently different pieces of the app are more mobile friendly than others. Need to do a usability audit of the app in mobile.

## Process
Log into the staging app as both admin and partner users and observe and log any weirdness in the mobile experience. Be sure to check...

Admin
- filing a support request
- viewing the app dashboard of all lockbox partners
- viewing the app dashboard of all support requests across partners
- viewing a single lockbox partner's activity
- adding cash to a single lockbox partner
- adding a new user to a single lockbox partner
- viewing a single support request
- viewing and adding notes to a support request
- changing the status of a support request
- updating account details
- updating password

Partner
- viewing and clicking to confirm an add cash alert
- viewing a reconciliation alert and reconciling the lockbox
- viewing the action needed tab
- updating the status of a support request from the action needed tab
- viewing the all activity tab
- viewing a single support request
- viewing and adding notes to a support request
- changing the status of a support request
- updating the lockbox partner details
- updating account details
- updating password

## Acceptance Criteria/Definition of Done
This is done when...
- [x] all the above functionality is audited for usability on a mobile device
- [x] each issue is a documented in a separate Github issue with screenshots and labeled "mobile work" and any other appropriate labels
- [x] all mobile wonkiness or poor usability is logged for follow up in a follow up issue

**Comment by jel535s** [comment]
Created audit trail document using above criteria: https://docs.google.com/spreadsheets/d/1iJUgUDqwH3m6Sdq0mpVp-vV_bMLh5mh7FF3Hq-NNPGw/edit?usp=sharing

**Comment by jel535s** [comment]
Audited all MAC user test cases, created #477  and #478 - need to create more tickets next week based on screenshots, and finish audit from the Partner user view.

**Comment by jel535s** [comment]
Audit completed and new tickets created to log all issues: #481 #482 #483
