### ISSUE TITLE
Lockbox manager not receiving low balance alerts

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#432]
## Context
The lockbox manager alerted that they are not receiving low balance alerts.

## Process
Investigate why the lockbox manager is not receiving these alerts. Is this a problem with missing env vars? With email delivery? With the code triggering the low balance alerts?

## Acceptance Criteria/Definition of Done
The lockbox manager _should_ receive low balance alert notifications

**Comment by nsiwnf** [comment]
@BintLopez Is this still a bug?

**Comment by gujacq** [comment]
Rolling this into #451.
