### ISSUE TITLE
Create one-pager for Lockbox

### ISSUE THREAD

**Issue by gujacq** [MidwestAccessCoalition/lockbox_rails#439]
## Context
Need one-pager for Lockbox explaining what this app is: What the product does, who are the users, core functionalities

## Process
Identify information that needs to be in the one-pager
Create copy
Create /design a PDF 

## Acceptance Criteria/Definition of Done
We create a PDF that explains the Lockbox, and people who review it understand what it means

**Comment by jel535s** [comment]
First draft for copy is here: https://docs.google.com/document/d/1hNdjw_62jTx8UH5V8sPpB0Tj3mIrerPxLXDyQI7sr8s/edit?usp=sharing
@gujacq  sending this to you for design. But I'm happy to talk through it as well, or provide edits as needed!

**Comment by gujacq** [comment]
Updated with a logo!
