### ISSUE TITLE
Improve low balance alerts and notification

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#451]
## Context
Low balance alerts should also include in app alerts being displayed and email notifications should go to lockbox manager, finance team, and all app admins.

## Process
- Partner alert should say:  "Your lockbox balance is below $[XX (threshold amount)]. The lockbox manager should be reaching out to you shortly. If you haven't heard from them in a few days, please email ENV['LOCKBOX_EMAIL']." This should be displayed in the same style and placement as all other partner alerts.
- Admin dashboard alert should say:  "[Partner name]'s balance of $[BALANCE] is below $[XX (threshold amount)]. Please replenish the funds." This should be displayed in the same style and placement as all other partner alerts that are displayed in the admin dash (main dash page, and the all activity tab of that partner).

## Acceptance Criteria/Definition of Done

- [ ] When a partner's trigger amount is hit, emails should be sent to ENV['LOCKBOX_EMAIL'],  ENV['LOW_BALANCE_ALERT_EMAIL'], and cc all users with "admin" role

- [ ] When a partner's balance is below the trigger amount, an alert should be displayed on both the partner and admin views. This alert will be displayed until the balance is above the trigger amount again. Note that the add cash alert will be displayed _above_ the low balance alert. When the partner confirms the add cash addition, these two alerts should disappear.

## Resources
Related to https://github.com/MidwestAccessCoalition/lockbox_rails/issues/371

**Comment by gujacq** [comment]
@nsiwnf is picking this one up
