### ISSUE TITLE
Resolve devise deprecation alert

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#455]
## Context
```
DEPRECATION WARNING: [Devise] `DeviseHelper.devise_error_messages!`
is deprecated and it will be removed in the next major version.
To customize the errors styles please run `rails g devise:views` and modify the
`devise/shared/error_messages` partial.
 (called from block in _app_views_devise_sessions_new_html_erb
```

## Process
- Run the app locally and watch the server logs to see this deprecation warning.
- Update references to the soon to be deprecated code

## Acceptance Criteria/Definition of Done
Update references in the views to deprecated code

## Resources
Devise docs

**Comment by scottyschup** [comment]
Duplicates #354
