### ISSUE TITLE
Make "Test" partner in prod invisible from the dashboard

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#466]
## Context
Currently, the test partner shows prominently in the prod dashboard. This should be hidden by default.

## Acceptance Criteria/Definition of Done
- test partner should not be visible in prod dashboard

## Resources
Add screenshots/mocks if relevant
Add relevant labels

**Comment by jel535s** [comment]
Not worth doing!
