### ISSUE TITLE
Determine user access tiers

### ISSUE THREAD

**Issue by gujacq** [MidwestAccessCoalition/lockbox_rails#470]
relates to conversations we've been having between #349 and #417 

## Context
We need to determine user access tiers

## Process
How do I recreate what you see? Give me the steps to get here.

## Acceptance Criteria/Definition of Done
What do you want to happen?
Possible fixes?

## Resources
Add screenshots/mocks if relevant
Add relevant labels

**Comment by jel535s** [comment]
MAC Leadership guidance on this was that we don't need to focus on user tiers- the functionality to add/delete MAC users and see/adjust finance categories is ok to share with all MAC emails.
