### ISSUE TITLE
Mobile - MAC user and Partner user - viewing and adding notes to a support request

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#482]
## Context
As our users are often accessing the app on mobile devices, we did an audit for usability on #424 

## Process
When signed in on mobile as a MAC user or as a Partner user, try to add a note to a Support Request. The text box is wider than the screen (using an iPhone SE 4.7 inch screen and Firefoxbrowser), and the view scrolls over while typing. Submit button for the note can only be seen by scrolling over, easter-egg style. See screenshots in Resources.

## Acceptance Criteria/Definition of Done
To better match the Invisio design in Resources, the Add a Note function should stay within the parameters of the screen.
Adjust the resizing of the text entry box so that the Submit button is visible without scrolling. 
Ideally, the text box also won't be larger than the screen to avoid the view automatically scrolling over while typing.

## Resources
Current state:
<img width="375" alt="MAC user adding a note to support request" src="https://user-images.githubusercontent.com/53353956/92336362-667c3280-f065-11ea-817e-3aebd026a0e0.png">
<img width="375" alt="MAC user adding a note to support request2" src="https://user-images.githubusercontent.com/53353956/92336363-68de8c80-f065-11ea-85d9-ca99bb9a3731.png">

Invision mobile design: (this shows the Support Request screen but does not show the "Add a Note" function engaged)
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/398800920

Desktop mock for comparison: https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/370232899

**Comment by scottyschup** [comment]
Note: this ticket addresses the reported issue, but this area of the app still has the following UI issues:
* table view not yet implemented for mobile (https://github.com/MidwestAccessCoalition/lockbox_rails/issues/526)
  https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/398800920
  Currently:
  <img width="282" alt="Screen Shot 2020-12-13 at 4 38 43 PM" src="https://user-images.githubusercontent.com/6441226/102026199-0d0d5900-3d62-11eb-969c-cd222ab854fd.png">
  <img width="288" alt="Screen Shot 2020-12-13 at 4 38 47 PM" src="https://user-images.githubusercontent.com/6441226/102026200-0da5ef80-3d62-11eb-8ddf-96931d39d4e0.png">
* secondary navbar menu—wrapped titles illegible
  <img width="287" alt="Screen Shot 2020-12-13 at 4 38 31 PM" src="https://user-images.githubusercontent.com/6441226/102026191-febf3d00-3d61-11eb-86d3-c02c3f8a476b.png">

**Comment by jel535s** [comment]
Looks like this PR was merged! Closing out our final MVP ticket, woo-hoo!
