### ISSUE TITLE
Potential rename from Lockbox

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#491]
## Context
In a conversation with MAC ED, potential to rename the lockbox came up. We should discuss this further.

## Process
TBD

## Acceptance Criteria/Definition of Done
TBD

## Resources
TBD

**Comment by BintLopez** [comment]
@gujacq @jel535s -- flagging for y'all. We should discuss further with Diana

**Comment by jel535s** [comment]
We're doing this.
