### ISSUE TITLE
Interview: a DevOps explanation/documentation of our deploy lifecycle

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#510]
## Context
To help onboard new members and to help all of our team members have more transparency on our process, we want to create a DevOps explanation/documentation of our deploy lifecycle in the Resources section of this Github.
Maybe we can bake into CI/Circle? 
@scottyschup could help @BintLopez write this up

## Process

- [ ] Interview DevOps team- at least 2 members

- [ ] collate notes and post in Resources

## Acceptance Criteria/Definition of Done
A useful doc exists with a high level DevOps explanation/documentation of our deploy lifecycle

**Comment by scottyschup** [comment]
> To help onboard new members and to help all of our team members have more transparency on our process, we want to create a DevOps explanation/documentation of our deploy lifecycle in the Resources section of this Github.
> Maybe we can bake into CI/Circle?

Can anyone clarify what "bake into CI/Circle" means?

**Comment by jel535s** [comment]
@scottyschup - I believe that note was from @BintLopez but that would also be a great question for our stand on Sunday

**Comment by jel535s** [comment]
Per conversation over Zoom, we don't want to include this in onboarding for new members at this time.
