### ISSUE TITLE
Design work: Adding terms of use and privacy policy

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#513]
## Context
To complete MVP of the Lockbox app, we want to have pages where we host a Terms of Service and Privacy Policy within the app.

## Process

- [x]  (Data Structure Design) Design where these docs will be hosted, as both documents indicate a stable URL within their body text to find "the most recent version"- @gujacq 
- [x] (App Page Design) Design where these will live in the app and produce Invisio design mockups for engineers to build - @gujacq 
- [x] Finalize Terms of Service and Privacy Policy documents
- [x] Get approval on those 2 documents from MAC Leadership on 4/8
- [x] Update #539 ticket in github to add these 2 designed and hosted document pages to be built into the Production instance of the Lockbox app - @jel535s 

## Acceptance Criteria/Definition of Done
For this ticket, Acceptance Criteria is to have all design work done and an engineering ticket fully scoped out.

## Resources
Terms of Service doc is currently being edited with MAC leadership here: https://drive.google.com/file/d/1QuHwMNPg8yByFdIzOouE6rkULwHBfdk6/view?usp=sharing

We do not currently have a privacy policy document. There are a number of sites that use forms to build a boilerplate Privacy Policy, which we could edit from there. Let’s consider whether any advertising or security concerns might come from using one of these:
https://app.termly.io/builder/documents/new?template_id=12
https://www.freeprivacypolicy.com/free-privacy-policy-generator/
https://www.termsfeed.com/privacy-policy-generator/
https://app.privacypolicies.com/wizard/privacy-policy
https://www.privacypolicytemplate.net/
https://www.privacy-policy-template.com/privacy-policy-generator
https://legaltemplates.net/form/privacy-policy/
https://midwestaccesscoalition.org/pages/privacy

**Comment by gujacq** [comment]
Privacy policy draft based on our MAC site privacy policy here: https://docs.google.com/document/d/1KZiExoGecVjZkoXqoBIzejPAXvYGxbZ3tzqyzKE9b8g/edit#

**Comment by gujacq** [comment]
Design here: https://invis.io/9EMYOUG7ZBA#/443101456_Dashboard_-_General-_Footer

![dashboard - general: footer](https://user-images.githubusercontent.com/33872753/105647796-9a69c000-5e6d-11eb-86d8-379ef681b2e6.png)

**Comment by jel535s** [comment]
Thanks @gujacq ! Can you clarify if we should continue hosting the privacy policy/terms of service on local google docs, or if "the most updated version" should be hosted in pages on the app? I ask just to clarify since the text of those documents will likely have a paragraph that indicates where users should access the most updated version.

**Comment by jel535s** [comment]
Confirmed via Slack- these will be hosted on the app and the "the most updated version" phrasing will be similar to the [Privacy Policy on the main MAC website here](https://midwestaccesscoalition.org/pages/privacy), something like, "CHANGES AND UPDATES TO THIS PRIVACY NOTICE
This Privacy Notice may be revised periodically and this will be reflected by the “effective date” above. Please revisit this page to stay aware of any changes."

**Comment by jel535s** [comment]
![image](https://user-images.githubusercontent.com/53353956/116011145-23b59d80-a5e9-11eb-9649-9123f4576df9.png)
Updated Dev ticket and moved to Ready to Work.
