### ISSUE TITLE
Design: Nav menu style clean-up

### ISSUE THREAD

**Issue by scottyschup** [MidwestAccessCoalition/lockbox_rails#525]
## Context
The nav menu looks a little sad due to inconsistent font sizes, margins, and borders and has less-than-ideal responsiveness at breakpoints. See images below.

### Desktop
Desktop looks ok since the inconsistently styled  components are not directly next to each other. 
<img width="871" alt="Screen Shot 2020-12-06 at 5 40 29 PM" src="https://user-images.githubusercontent.com/6441226/101296699-7503f280-37ea-11eb-9d99-5b902e365260.png">

### Breakpoint
But at the breakpoint, everything looks a little awkward and squished.
<img width="636" alt="Screen Shot 2020-12-06 at 5 41 55 PM" src="https://user-images.githubusercontent.com/6441226/101296700-759c8900-37ea-11eb-92b3-ed92604fa735.png">

### Mobile
And in mobile, the different font-sizes, margins, and borders make for a very thrown-together look that could be significantly improved.
<img width="280" alt="Screen Shot 2020-12-06 at 5 54 15 PM" src="https://user-images.githubusercontent.com/6441226/101296994-2f482980-37ec-11eb-9d8f-f81d2bf712c1.png">
<img width="338" alt="Screen Shot 2020-12-06 at 5 54 39 PM" src="https://user-images.githubusercontent.com/6441226/101296995-2fe0c000-37ec-11eb-989e-547afb7394ba.png">

## Acceptance Criteria/Definition of Done
It looks pretty at any screen resolution.

## Resources
The menu has changed a bit since the initial mocks, but here's one for reference: https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/408360708

**Comment by jasonwynkoop86** [comment]
Fixes for this. 
Change the break point for the nav window toa higher pixel count so it switches to a mobile single file at a higher pixel width to remove them butting up against each other. 

Change the header container to be 100% from 80% to remove some left alignment issues

Change button width to 100% of container and change padding and margin to 
padding: 12px 3px
Margin: 12px 0px

![image](https://user-images.githubusercontent.com/82782739/119278945-332b0500-bbee-11eb-8846-e1a0722769d2.png)

**Comment by jel535s** [comment]
These look great! #610 created for dev work on this.
