### ISSUE TITLE
Fix support requests table in mobile

### ISSUE THREAD

**Issue by scottyschup** [MidwestAccessCoalition/lockbox_rails#526]
## Context
Currently in mobile, the support requests table, using Bootstrap data-tables styling, has a CSS rule that applies `max-width: none !important` to the data-table which causes the view to be wider than the rest of the page with the result that the header and other full-width elements no longer expand horizontally to fill the width of the page as they should.

<img width="321" alt="Screen Shot 2020-12-06 at 6 42 14 PM" src="https://user-images.githubusercontent.com/6441226/101298764-1ee87c80-37f5-11eb-9f24-e8f8c93a5bad.png">

## Process
Log in using the `cats@test.com` account and navigate to `/support_requests`.

## Acceptance Criteria/Definition of Done
Remove Bootstrap data-table classes for sure (why would they even use `!important` in a 3rd-party style library to begin with?!).

Possibly redesign the entire table for mobile view. Maybe something more like support request notes: https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/398800920

**Comment by scottyschup** [comment]
The InVision link to the support request notes table that I put in the description has not actually been implemented yet in the app. So if there's a ticket for that, this one could be combined with that since the relevant styling will likely be similar. Or if there's not already a ticket, this one could be expanded to include both tables.

**Comment by jel535s** [comment]
I'm wondering if #478  will fix this issue? If it's a different issue, then let's chat next week so I can understand a bit better and adjust the ticket scopes if needed.

**Comment by scottyschup** [comment]
> I'm wondering if #478 will fix this issue? If it's a different issue, then let's chat next week so I can understand a bit better and adjust the ticket scopes if needed.

#478 could fix it, but based on the acceptance criteria, that ticket looks more like a discovery/analysis ticket. I didn't see any clear specs other than to determine what needs to be done and come up with clearer specs. Not that this ticket really adds anything, except the suggestion that a new mobile support requests table could be modeled after the mobile support request notes table in https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/398800920. 

So yeah, this ticket could be closed as a duplicate, or if #478 gets broken up (and I think it probably should) this could be the ticket for the specific issues related to the mobile view of the support requests table.

**Comment by jel535s** [comment]
Based on conversations today, we will look at redesigning tables for 2.0 when Jacqui is back.

**Comment by jel535s** [comment]
This should be resolved by the Piggybank redesign.
