### ISSUE TITLE
Investigate and improve flaky test - support requests controller

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#531]
## Context
The `spec/controllers/lockbox_partners/support_requests_controller_spec.rb` has been flaky. This should be investigated and improved upon. @scottyschup has suggested an improvement to make the call 10 times and taking an average. See:  

## Process
- Reproduce the flakiness
- Improve the test such that it no longer fails intermittently

## Acceptance Criteria/Definition of Done
- improvement to the test so that flaky failures no longer occur

**Comment by nsiwnf** [comment]
@BintLopez @scottyschup  when was the last time this failed? Im having trouble finding an example in the test workflow

**Comment by nsiwnf** [comment]
Unassigned myself - not sure I have enough context atm

**Comment by jel535s** [comment]
As we were not able to reproduce this, @BintLopez may close this ticket out.
