### ISSUE TITLE
Backfill data to support PII redaction

### ISSUE THREAD

**Issue by kyaroch** [MidwestAccessCoalition/lockbox_rails#567]
## Context
In #467 and #555, we put code in place to automatically redact possible PII from support requests and associated notes 90 days after the support request was closed, and prevent paper_trail from recording changes to `support_requests.name_or_alias`. However, this won't work for support requests that were created before that code was deployed, since the close date was not recorded.

## Acceptance Criteria/Definition of Done
* Create a rake task to backfill `lockbox_actions.closed_at` with the value of `lockbox_actions.updated_at` where `closed_at` is null and the status is `"completed"` or `"canceled"`.
* Create a rake task to delete any `versions` records where `object_changes` contains `"name_or_alias"`.

## Resources
Add screenshots/mocks if relevant
Add relevant labels

**Comment by BintLopez** [comment]
> Create a rake task to backfill lockbox_actions.closed_at with the value of lockbox_actions.updated_at where closed_at is null

AND where the lockbox_action is NOT in pending status

@kyaroch ^^
