### ISSUE TITLE
Frontend: Edit login page to include a fun gif

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#572]
## Context
Currently our landing page is very plain. Let's add some fun gifs!

## Process
Navigate to the production instance of the app here: http://mac-lockbox.herokuapp.com/ Notice that it's a very dull landing page.

NEEDED: instructions for a new dev to help get them started in adding a gif here. Where do they add the gifs, for example?

## Acceptance Criteria/Definition of Done
On the landing page at http://mac-lockbox.herokuapp.com/, a fun gif loads below the "Protected by sqreen" icon.

## Resources
Current landing page:
![image](https://user-images.githubusercontent.com/53353956/109443494-4e77e100-7a00-11eb-932d-436e2ad2bce2.png)

**Comment by BintLopez** [comment]
Love it! For reference, here's what the DARIA app's log in page looks like
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/5728859/110253432-4b2caa00-7f58-11eb-9925-8af419b2839c.png">

The message to the right of the login section is randomly selected from a list of nice notes that developers have left for DARIA case managers. DARIA team has worked this into their onboarding experience as well for developers by making an onboarding task for anybody new to working on the repo to add a nice message https://github.com/DCAFEngineering/dcaf_case_management/issues/884

That's what we're going for here, but with cute gifs. If gifs are too difficult or busy, we could also scale back to a nice message.
