### ISSUE TITLE
Pair (MAC + Reprocare): Add color change to balance line when the trigger amount is met

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#573]
## Context
As a MAC user, I want to see which partner's balances are below the trigger amount as I'm scrolling down my dashboard.

## Process
When a MAC user logs in to the app, they can see all of the partners on their dashboard. 
When a partner's balance drops below the trigger amount, we have functionality that emails MAC's finance team and also creates a red alert on the partner dashboard (see screenshot below). However, when scrolling down through the partner list those alerts are hidden.

To resolve this, we want to add color change to the line showing the partner's name and balance as a MAC user scrolls down their dashboard. The color should be different when the partner's balance drops below the balance alert threshold (yellow?), vs when it's zero or below zero (red?)

## Acceptance Criteria/Definition of Done
When a partner has a balance below the trigger amount, a color change is activated on all MAC user dashboards that highlights the partner's name and their balance (see mockup below). When the balance hits or drops below zero, that color should change again.

## Resources
Red alert on MAC partner dashboard:
![image](https://user-images.githubusercontent.com/53353956/109444232-618bb080-7a02-11eb-8fca-e917d7ca5289.png)

Mockup of new color addition:
![MAC partner dashboard](https://user-images.githubusercontent.com/53353956/109444385-bcbda300-7a02-11eb-9034-c03f01030d12.jpg)

**Comment by BintLopez** [comment]
One question for this task -- should the color be different when below the balance alert threshold vs when it's zero or below?

**Comment by jel535s** [comment]
That's a great question, and I'll adjust it in the scope above!

**Comment by jel535s** [comment]
Nicole merged this PR 6/27
