### ISSUE TITLE
Design: MAC user needs ability to confirm a "cash add" for a partner

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#576]
## Context
We’ve recently encountered a scenario where one of the partners did not confirm receipt of cash in the app and the balance appeared to be dangerously low when it wasn’t. The partner user confirmed via Signal message that they had the cash but did not confirm it in the app. In that scenario, it would also be ideal for an “admin” user to be able to force confirm an “add cash” lockbox action via the UI.

## Process
Currently, only a partner can confirm their cash add receipt, by clicking on the banner that appears on their dashboard when cash has been sent. However, we are finding in real-world user stories that sometimes balances are not being updated via this banner and in fact the MAC coordinators or finance team are being contacted via email or Signal messages notifying them that the cash ad has been received. 

Although this is edge case behavior, we want to add functionality for MAC users to for an “admin” user to be able to force confirm an “add cash” lockbox action via the UI.

Some possible locations for this new button:
When a MAC user signs in and a cash add hasn't been confirmed in over 30 days, a banner shows up at the top of the dashboard (see Resources). 
1. add a link on that banner to either confirm the cash add, or that link takes us to the partner's details page where we would add a confirm action to the Cash Add line item?
2. add an action to the Cash Add line item, similar to the View Details button for Support Requests. This would also require designing an "update" page for Cash Adds which does not currently exist. (see Resources)

## Acceptance Criteria/Definition of Done
**Design** where MAC "admin" users should be able to force confirm an “add cash” lockbox action via the UI. Create invisio or other design mockups that engineers can use to implement this on #575 .

## Resources
We generally use Invisio to mockup these designs, and @gujacq can share access with you as needed!

Dashboard with a banner as noted above:
![image](https://user-images.githubusercontent.com/53353956/110257510-e11a0200-7f63-11eb-8887-af518e1705a6.png)

Partner Dashboard, where we might add an action to the Cash Add line item:
![image](https://user-images.githubusercontent.com/53353956/110257524-f5f69580-7f63-11eb-970c-34c48dabc2fc.png)

Partner dashboard, showing action currently for Support Requests:
![image](https://user-images.githubusercontent.com/53353956/110257641-6c939300-7f64-11eb-8b1f-9da66283448b.png)

**Comment by jasonwynkoop86** [comment]
Cash add link in farthest cell to the right. 
![image](https://user-images.githubusercontent.com/82782739/119277950-0bd13980-bbe8-11eb-8830-1a25b1c4a5bd.png)

Cash add screen for updating the proper fields to confirm
![image](https://user-images.githubusercontent.com/82782739/119278185-438cb100-bbe9-11eb-95b9-8cdd7926fd9b.png)

Confirm/edit cash add field
![image](https://user-images.githubusercontent.com/82782739/119278108-d1b46780-bbe8-11eb-9b5c-565f1955ddb5.png)

**Comment by jel535s** [comment]
Hey @jasonwynkoop86 ! Thank you so much for jumping right on this one! Could we change the wording slightly on the first mockup ("Cash add link in farthest cell to the right.")? I'm thinking it could read "Confirm Cash Add" or "Edit Cash Add", just to clarify that by clicking that link, they are not adding more cash to the partner balance, but are editing/confirming the existing line item?

**Comment by jasonwynkoop86** [comment]
Sounds great!. 
here is the change. 
![image](https://user-images.githubusercontent.com/82782739/119278485-353f9480-bbeb-11eb-84d5-11cad8188a06.png)

**Comment by jel535s** [comment]
These look great! updating the related dev ticket now.
