### ISSUE TITLE
Design:  allow an “admin” user to delete a reconciliation action through the UI

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#578]
## Context
We’ve had multiple occasions now where a clinic partner inputs the incorrect amount for reconciliation. The best resolution for this is to just delete the event, which will just trigger reconciliation alerts for that partner again the next time they log in. Currently the only way we’re resolving this is super manually through heroku console, which is fairly cumbersome for the team.

## Process
We're thinking the way that this could simply fit into the existing UI is by either:
1. adding a link to delete that record directly to the table under “actions” (see below screenshot) or
2. by linking to a separate reconciliation page where they could delete

## Acceptance Criteria/Definition of Done
**Design** mockups for engineers to build on #577 . Designs need to show where the "delete" action will live, and if needed, a new reconciliation update page where they could delete that most recent reconciliation.

## Resources
Current Lockbox table on Partner dashboard as viewed by a MAC admin: 
![image (1)](https://user-images.githubusercontent.com/53353956/110257269-bbd8c400-7f62-11eb-8234-28689fdd1b18.png)

**Comment by jasonwynkoop86** [comment]
https://www.figma.com/proto/xhSGqoMxLZOqQX5d3eS7DF/LockBox-Reconciliation?node-id=2%3A2&scaling=min-zoom&page-id=0%3A1

design prototype for a workflow of how reconciliations would work on the admin side.

**Comment by jel535s** [comment]
Will need slight modification to the design to indicate deleting, rather than editing, the reconciliation.

**Comment by jasonwynkoop86** [comment]
Prototype has been updated, using the original link and pasted again here for convience. 
https://www.figma.com/proto/xhSGqoMxLZOqQX5d3eS7DF/LockBox-Reconciliation?node-id=3%3A13&scaling=min-zoom&page-id=0%3A1

basic flow description. 
-delete the reconciliation link to the right of the ledger. 
- detail screen for deleting the reconciliation 
- link back to the ledger with reconciliation still on the ledger but amounts updated and reconcile with text slash added to all elements. and an info icon with date deleted and the user who deleted it. 

possible questions. 
should there be another confirmation screen before deleting it?

**Comment by jel535s** [comment]
This design is approved!
