### ISSUE TITLE
Dev: Combine "Edit Profile" and "Account Settings"/"Update Password"

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#589]
## Context
Currently in the app, users have 2 places where they can make updates unique to their profile.
"Edit Profile" takes them to a page headed "Update User", where they can change their profile name and time zone (see screenshot in Resources below). Soon this page will also include notification preferences for Funder users only, once work on #587 is complete.
"Update Password" takes them to a page headed "Update Password" where they can.... change their password. (screenshot below in Resources)

We want to combine these two pages into one page called "Account Settings".

## Process
We want to combine these two pages into one page called "Account Settings". New designs shouldn't be needed since the page designs should not change much from how they look currently. The order on the page should be:

1. Name field
2. timezone field
3. password fields
4. if a Funder user, notification preferences (if you're starting this before #587 is completed, give the PM and the dev on that ticket a heads up as it will affect their work).

## Acceptance Criteria/Definition of Done
On this page, every user should be able to:

- change their name
- change their timezone
- update their password

And once #587 is complete, on this page Funder users should also be able to:

- choose between two email notification options

## Resources
Edit Profile page:
![image](https://user-images.githubusercontent.com/53353956/112771804-3d1bf780-8ff3-11eb-820b-e758f93a28a1.png)
Update Password page:
![image](https://user-images.githubusercontent.com/53353956/112771879-97b55380-8ff3-11eb-82e9-7aa6260b582b.png)

**Comment by nsiwnf** [comment]
@jel535s Should "Account settings" be the where the Edit Profile button is or the Update Password  button?

**Comment by jel535s** [comment]
@nsiwnf let's put it where the "Update Password" button is- on the right hand side. And then the only thing under their contact info will be "Edit Contact Information".
