### ISSUE TITLE
Create a support request mockups

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#59]
As a MAC user, I can fill out a form to create a support request

Data needed to create the support request includes...
- pickup date (lockbox_action date)
- client alias (support request)
- lockbox partner (associated to support request and lockbox action)
- urgency flag (support request)
- breakdown of the amounts (category and amount --> lockbox transaction)

**Comment by gujacq** [comment]
Breakdown of amounts:

$$ & dropdown of categories (gas, parking, transit, child care, medicine, food, adjustment)

Total is automatically calculated

**Comment by gujacq** [comment]
Mock-up so far: https://invis.io/9EMYOUG7ZBA#/361599958_dashboard_-_MAC_User_-File_Support_Request-

**Comment by gujacq** [comment]
FYI, I've added another mock for filing a support request from the MAC user dashboard. This is needed bc it's not tied to a particular partner yet, so here's what that looks like:

https://invis.io/9EMYOUG7ZBA#/365424956_dashboard_-_MAC_-file_Support_Request_Agnostic-

cc: @BintLopez
