### ISSUE TITLE
Locked users are receiving some notifications

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#596]
## Context
A current lockbox partner advised us that a locked user account is currently receiving Add Cash email notifications. If a user's account is locked, they should **not** receive any email notifications from the app.

## Process
- Reproduce the buggy behavior (locked user receiving email notifications for Add Cash action)
- Investigate whether it's just add cash notifications or whether reconciliation, support request, or other notifications trigger emails to locked users
- Create a failing test to confirm the bug and ensure that suppressing these notifications for locked users works

## Acceptance Criteria/Definition of Done
- Locked users should not receive any email notifications
- Automated tests should confirm both the bug and the fix

**Comment by nsiwnf** [comment]
@BintLopez I see Users can have statuses `active`, `locked` and `pending` - should `pending` Users get notifications as well?

**Comment by BintLopez** [comment]
@nsiwnf great question! Pending users should not be getting notifications either.
