### ISSUE TITLE
Create active method on LockboxPartner

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#69]
A LockboxPartner should only be considered active once it's received $$ and also when a partner user has been added to the account:

Criteria for an active LockboxPartner entails...

- at least one add cash lockbox action in completed status
- at least one confirmed user for that lockbox partner

Actions that should be restricted to only an 'active' lockbox partner are...

- filing a support request
- reconciliation

**Comment by kyaroch** [comment]
Implemented in https://github.com/MidwestAccessCoalition/lockbox_rails/pull/71
