### ISSUE TITLE
Update the styling for Support Request status dropdown for MAC users

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#88]
# CURRENT SPEC:
https://github.com/MidwestAccessCoalition/lockbox_rails/issues/88#issuecomment-522821934

# OLD SPEC (context)
As a MAC user, I may sometimes want to update the amount to be disbursed to a client. Currently when coordinators need to do this, they fill out another lockbox request form for the same client. In the app, this should be handled by the update support request functionality.

If the amount or pickup date changes, the lockbox partner should receive a notification email 

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/5728859/58388240-ee116f80-7fe1-11e9-9576-30012bfc650c.png">

**Comment by BintLopez** [comment]
For after launch / post MVP release, we should think about what in-app notifications should look like. Aka in the event that the amount changes on a case, can we have a visual indicator that something changed.

**Comment by BintLopez** [comment]
@gujacq What should the editing mode look like for a support request? We could potentially just make everything in this view turn into form inputs?

**Comment by gujacq** [comment]
@BintLopez Here it is: https://invis.io/9EMYOUG7ZBA#/370233487_dashboard_-_MAC_User_-File_Support_Request_EDIT-

Basically it takes you to the same form page, but with everything filled out with the ability to edit.

**Comment by BintLopez** [comment]
Mockups complete, creating new task for implementation

**Comment by BintLopez** [comment]
MAC users need to be able to update the status of a support request as well. Should this be available from the edit view or from the main support request page?

- Note -- from an implementation perspective, it's easier to have the status be updated from the main support request page vs the edit mode form (as the edit form is leveraging the same code from a new support request form)

**Comment by BintLopez** [comment]
@gujacq just one question here re updating the status ^^

**Comment by gujacq** [comment]
@BintLopez and @rebeldroid12 updated the designs: https://invis.io/9EMYOUG7ZBA#/367773078_dashboard_-_MAC_User_-Single_Support_Request_-_Back_To_Dashboard-

(If you click on "Update Status" you'll get a dropdown that shows what a current selection looks like as well as hover. Attaching screenshots)

<img width="920" alt="Screen Shot 2019-08-19 at 9 02 43 PM" src="https://user-images.githubusercontent.com/33872753/63311810-f61d3a80-c2c4-11e9-90b6-e8ffdc742399.png">
<img width="941" alt="Screen Shot 2019-08-19 at 9 02 54 PM" src="https://user-images.githubusercontent.com/33872753/63311811-f6b5d100-c2c4-11e9-924e-a5062d637299.png">

**Comment by jel535s** [comment]
This design looks great, I think is ready to work.

**Comment by jel535s** [comment]
@misternu

**Comment by jel535s** [comment]
Use the above (most recent- Aug 19) designs to update the status dropdown for MAC users.

**Comment by BintLopez** [comment]
The functionality of this task is working, so the underlying functionality does not need to change. The scope of this task is to make the actual views match the dropdown and styling present in the mockups.
