### ISSUE TITLE
Lockbox Partner notifications

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#89]
There are a few events that should trigger notification emails to a lockbox partner...

- support request creation
- new note on a support request
- changed date or amount of a support request
- cash addition to the lockbox
- reconciliation reminder

## Acceptance Criteria
- Copy for the mailers for each of the above actions (subject line and email body)
- Creation of tasks for each of these mailers

**Comment by jel535s** [comment]
The copy for this will relate to #157

**Comment by jel535s** [comment]
Tickets created for:
support request creation
new note on a support request
changed date on Support Request, changed date or amount of a support request


Need tickets still for:
cash addition to the lockbox
reconciliation reminder

**Comment by jel535s** [comment]
Tickets all created!
